### ISSUE TITLE
Just a request

### ISSUE THREAD

**Issue by GrouikGrouik** [Free-IPTV/Countries#103]
Hello,

Really a big thank you for your work,
This allows me to watch IPTV on my Kodi & it's very fun.

I contact you here - I don't know if I should do it there or elsewhere :/ -.

I would like to paste all the German lists to form only one.

Problem is, I'm really bad at programming and I don't know the language used to create all these lists.
In short, every time I try, it doesn't work.

Do you have the time (and the will) to give a little lesson to a real noob like me? Please....

My project would be to start from that list and add a list of all German radio stations.

But that, I can do it only on condition of having understood how it works and to train myself in this programming language (if only I knew which one it is...) 

Best regards
GrouikGrouik

**Comment by Free-IPTV** [comment]
Hi GrouikGrouik,

to merge multiple M3U´s into one for the IPTV Simple Client in Kodi, i use the Add-on IPTV Merge from Matt Huisman (NZ) Information about this an help find you here:

https://forums.whirlpool.net.au/thread/9x2zlv09

I hve only a very long list of all M3U´s in the ZZ_PLAYLIST_ALL_TV.m3u here in my Repo. You can use this M3u as remote location in the IPTV Simple Client in Kodi, type only in zhe field of remote location this shortcut:

https://is.gd/freeiptvall

For the radio stations the M3U the entryies should like this:

#EXTM3U
#EXTINF:-1 tvg-name="AFN Radio" group-title="RADIO" radio="true" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/f/f2/AFN_TV.jpg",AFN Radio
http://14953.live.streamtheworld.com/AFN_LGY.mp3
#EXTINF:-1 tvg-name="Fun Radio 92.7 Alabama" group-title="RADIO" radio="true" tvg-logo="https://upload.wikimedia.org/wikipedia/en/4/4a/WAFN-FM_logo.png",Fun Radio 92.7 Alabama
http://edge1-b.exa.live365.net/a20884_live365
... and so on.

Greetings from Germany :-)
