### ISSUE TITLE
Portugal links

### ISSUE THREAD

**Issue by gomezpt** [Free-IPTV/Countries#104]
Hello,

Can you please include this for Portugal ?

https://m3upt.com/#dados
https://ptiptv.tk/

Thanks

**Comment by Free-IPTV** [comment]
Hi,

.tk is not Portugal, i thing, this stream is not legal, sorry

**Comment by gomezpt** [comment]
Hello,

They are legal, i can guarantee you. This tk website is a project like yours, only for Portugal.
The autor only includes open and legal streams made available by the providers.
Most of it are already referenced by the 1st link (m3upt).

Regards.

**Comment by Free-IPTV** [comment]
For example

RTP 1 is geoblocked! ptiptv.tk in NOT the original streaming provider. Sorry!

#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36
https://ptiptv.tk/rtp1.m3u8

**Comment by Free-IPTV** [comment]
and this is NOT allowed...

"The autor only includes open and legal streams made available by the providers." Only RTP 1 has the Right of the Streams, NOT .tk. My Projekt here is legal! .TK isn´t! 

Bye

**Comment by Free-IPTV** [comment]
Next exanple, THIS is the original Stream, not this shit gtom .tk!!!

https://streaming-live.rtp.pt/liverepeater/smil:rtp1HD.smil/chunklist_b2540000_slpor.m3u8?pxt_rtp

**https://streaming-live.rtp.pt/**

**Comment by gomezpt** [comment]
Yes, RTP 1 is geoblocked. Like some French/German channels that i can only access with VPN.
You can find the original link in the m3upt (https://m3upt.com/iptv), the same for SIC and TVI

# TV
#EXTINF:-1 group-title="TV" tvg-id="RTP 1" tvg-logo="https://m3upt.com/logos/RTP1.png",RTP 1
https://streaming-live.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8

**Comment by Free-IPTV** [comment]
**My project only includes freely available and legal streams that anyone can receive. No trick, no VPN crap and so on. Discussion is over!**

**Comment by gomezpt** [comment]
I dont know why the tk project offuscates the real URL.. 
but you can consider the m3upt

**Comment by gomezpt** [comment]
Ok, thanks anyway. It was just a suggestion ;)
