### ISSUE TITLE
Israel channels

### ISSUE THREAD

**Issue by vistad** [Free-IPTV/Countries#109]
I wanted to recommend the new great app - Hypnotix - to my friend who is interested in Israel TV stations, and found there are no Israel channels. Why?

**Comment by Free-IPTV** [comment]
I have nothing to do with the Hypnotix app!

**Comment by Free-IPTV** [comment]
Sorry, I've only just found out that Hypnotix uses my M3Us. Unfortunately, I don't have an M3U for Israel. I now have over 3000 streams here in my repo. I would need support for the M3U for Israel. I thank you. :-)

**Comment by Free-IPTV** [comment]
Hi,

today i has create the new IL01_ISRAEL.m3u. In the Playlist ALL the station you found at number: 2664 - 2670

**Comment by vistad** [comment]
Thank you! 😀👍

**Comment by vistad** [comment]
I'm sorry - it does not work.
How should one use it?
Will you integrate it into your general list of channels?
I tried to integrate new channels into your list - but it gets overwritten
in 3 minutes.
Thanks!

**Comment by Free-IPTV** [comment]
Hi  vistad ,

sorry, I don't know the Hypnotics app. You have to contact Hypnotics' support. I only make the M3U's available to everyone. The new IL01_ISRAEL.m3u works and the new streams from Israel are also in the ZZ_PLAYLIST_ALL_TV.m3u. It works on Kodi. So please ask the Hypnotics support. I thank you

**Comment by vistad** [comment]
You do enormous work, you are very busy perhaps.
The last question:
To subscribe to your main list - do I have to indicate your URL in my
Android player?
Or download your m3u list?
Thank you!

**Comment by Free-IPTV** [comment]
Hi Vistad,

it´s better you use the main list online. So you have always the the current list. The ZZ_PLAYLIST_ALL_TV you can load with this short path:

https://is.gd/freeiptvall

Greetings from Germany
FreeIPTV

**Comment by vistad** [comment]
Thank you!
Danke schön!
👍
