### ISSUE TITLE
line space problem

### ISSUE THREAD

**Issue by israelchoen** [Free-IPTV/Countries#11]
Hi
I use Playlist Loader addon, and pluto.tv links do not work because there is a line space between the #EXTINF and the https link.
I'd love it if you could delete the spaces.
Thanks

**Comment by Free-IPTV** [comment]
Hi israelchoen, i am using the iptx-merge addon and the iptv simple client, there ist no problem with spaces. I think, your playlist loader is the problem. ;-) I am remove the spaces and make a new upload of the  US07_USA_Pluto.m3u.

**Comment by israelchoen** [comment]
I installed [this version](https://github.com/Nux007/Kodi-plugin.video.playlistLoader) of the Playlist Loader addon
And now there is no problem even when there are spaces
Thanks!!

**Comment by Free-IPTV** [comment]
I´s using the addon iptv-merge from Matts Huisman. With this tool you can add the files you want to view and it makes one file fot zhe IPTV Simple Client. Thank you.
