### ISSUE TITLE
Geoblocked streams

### ISSUE THREAD

**Issue by musuruan** [Free-IPTV/Countries#118]
Hi!
The following German streams in DE01_GERMANY.m3u seem to be geoblocked:

- ZDF HD
- ZDFinfo
- ARTE
- 3Sat
- ServusTV HD
- ZDFneo
- ONE HD
- Radio Bremen TV HD
- MDR SACHSEN
- MDR SACHSEN-ANHALT
- MDR THÜRINGEN
- rbb Berlin
- SWR BW
- BR Fernsehen
- Phoenix
- WELT
- WELT Live Stream
- FIFA Club WM
- Sky Sport News HD
- Kika
- Nickelodeon

BR,

Andrea

**Comment by Free-IPTV** [comment]
Hi Musuruan,

Yes, that can be, but I and many from the German Kodi forum use this list. Some streams are actually only GEO-blocked for certain programs.
