### ISSUE TITLE
DE04_GERMANY_Pluto.m3u

### ISSUE THREAD

**Issue by maf-o** [Free-IPTV/Countries#139]
id identical for
  Totally Turtles nick and Teen nick
  5f0d668b872e4400073acc68 <-- is Teen nick

m3u identical for
  Totally Turtles nick and Teen nick
  5f0d668b872e4400073acc68 <-- is Teen nick
  
  nickrewind , kids jr. and World Poker Tour
  5ad9b7aae738977e2c312132 <-- is World Poker Tour

**Comment by Free-IPTV** [comment]
> 
> 
> id identical for
> Totally Turtles nick and Teen nick
> 5f0d668b872e4400073acc68 <-- is Teen nick
> 
> m3u identical for
> Totally Turtles nick and Teen nick
> 5f0d668b872e4400073acc68 <-- is Teen nick
> 
> nickrewind , kids jr. and World Poker Tour
> 5ad9b7aae738977e2c312132 <-- is World Poker Tour

Hi maf-o,

thanks for your information. We correct this romorrow, then commes the update. :-)

**Comment by maf-o** [comment]
comedy central made in germany is not broadcasting or is not correct
maybe you have a look on that channel too

**Comment by Free-IPTV** [comment]
> 
> 
> comedy central made in germany is not broadcasting or is not correct
> maybe you have a look on that channel too

okay, thank you! :-) When all channels are correct, i send you a message here, tomorrow. ;-)

**Comment by maf-o** [comment]
can you add people are awsome?
its on officle side of pluto TV

kind regards

**Comment by Free-IPTV** [comment]
> 
> 
> can you add people are awsome?
> its on officle site of pluto TV
> 
> kind regards

Hi maf-o

okay, i add this channel!

**Comment by CHJ85** [comment]
@maf-o Thanks for reporting these problems.
Everything's been fixed now and @Free-IPTV added the "People Are Awesome" channel.
