### ISSUE TITLE
Mexico M3U (made to accompany the Pluto MX m3u)

### ISSUE THREAD

**Issue by nrichw-eta** [Free-IPTV/Countries#158]
#EXTM3U 
#EXTINF -1 tvg-id="" tvg-name="Canal 10" tvg-country="MX" tvg-language="Spanish"  tvg-logo="https://www.lyngsat-stream.com/logo/tv/cc/canal_10_mx.png" group-title="MEXICO",Canal 10
https://www.canal10.tv/live/tvlive1/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Canal 14" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://i.pinimg.com/originals/03/6f/40/036f4070518a96473a811c3d34b2d285.jpg" group-title="MEXICO",Canal 14
https://d3nljkrx6mjqra.cloudfront.net/out/v1/1b9d9efd27814b3b8dc570113ae54409/index.m3u8
#EXTINF -1 tvg-id="" tvg-name="Canal 15 Summa Saberes" tvg-country="MX" tvg-language="Spanish"  tvg-logo="https://www.lyngsat.com/logo/tv/ii/ilce-canal-15-summa-saberes-mx.png" group-title="MEXICO",Canal 15 Summa Saberes
https://icsbaldeastd.aldeasolutions.mx/EVLiveCan15ABR/_definst_/mp4:12G27TMY/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="CORTV" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://www.lyngsat.com/logo/tv/cc/cor-tv-mx.png" group-title="MEXICO",CORTV
https://stream.oursnetworktv.com/latin/encoder29/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Jalisco TV 17.1" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://www.lyngsat-logo.com/logo/tv/jj/jalisco-tv-mx.png" group-title="MEXICO",Jalisco TV 17.1
https://5fa5de1a545ae.streamlock.net/sisjalisciense/sisjalisciense/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Mexico Travel Channel" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",Mexico Travel Channel
https://stream-02.nyc.dailymotion.com/sec(ekpi6JmRB5KslkTtNqtBmmYUue5BolDDN2KTsNL2ICQ)/dm/3/x7xyu4v/s/live-0.m3u8
#EXTINF -1 tvg-id="" tvg-name="Quiero TV" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://yt3.ggpht.com/a-/AAuE7mA6NAaaJM9k0gcBTmpG8qASqfkrXwRb0NQ0Zw=s900-mo-c-c0xffffffff-rj-k-no" group-title="MEXICO",Quiero TV
https://quierotvlive.tk/httplive/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="SET 26.1" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://www.lyngsat-stream.com/logo/tv/ss/set-tv-mx.png" group-title="MEXICO",SET 26.1
http://189.240.210.28:1935/envivo/puecom/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="SET 26.2" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://www.lyngsat-stream.com/logo/tv/ss/set-tv-mx.png" group-title="MEXICO",SET 26.2
http://189.240.210.28:1935/live/setpuebla/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="SMTV" tvg-country="MX" tvg-language="Spanish" tvg-logo="https://www.lyngsat-stream.com/logo/tv/ss/set-tv-mx.png" group-title="MEXICO",SMTV
https://6011c5681d877.streamlock.net:1936/enlinea/enlinea/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Más" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Más
https://5ca9af4645e15.streamlock.net/rtv/videortv/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Cuatro" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Cuatro
https://5f1af61612fb5.streamlock.net/tv4/videotv4_720p/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Cuatro 4.2" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Cuatro 4.2
https://5f2c1b0d880e5.streamlock.net/tv42/videotv42_720p/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Cuatro 4.3" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Cuatro 4.3
https://5f1af61612fb5.streamlock.net/tv43/videotv43_720p/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Mexiquense" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Mexiquense
https://5ca3e84a76d30.streamlock.net/mexiquense/videomexiquense/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9Mi8yMS8yMDIxIDExOjIxOjU4IFBNJmhhc2hfdmFsdWU9U2UxNVJPMGE2YmVBVmpBdFp3OVhkUT09JnZhbGlkbWludXRlcz01JmlkPQ==
#EXTINF -1 tvg-id="" tvg-name="AMX Noticias" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",AMX Noticias
https://5e50264bd6766.streamlock.net/mexiquense2/videomexiquense2/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV Nuevo León" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV Nuevo León
https://6011c5681d877.streamlock.net:1936/canal28/canal28/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="TV UNAM" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",TV UNAM
https://5fc584f3f19c9.streamlock.net/tvunam/videotvunam/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Telemar" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",Telemar
https://59d39900ebfb8.streamlock.net/8410/8410/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Telemax" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",Telemax
https://6011c5681d877.streamlock.net:1936/telemax/telemax/playlist.m3u8
#EXTINF -1 tvg-id="" tvg-name="Tlaxcala Televisión" tvg-country="MX" tvg-language="Spanish" tvg-logo=" " group-title="MEXICO",Tlaxcala Televisión 
https://vid.mega00.com:5443/LiveApp/streams/928111829917388844551988/928111829917388844551988.m3u8

**Comment by Free-IPTV** [comment]
Hi nrichw-eta,

thanks for this list. My repo also makes a lot of work, please note my readme:

https://github.com/Free-IPTV/Countries#countries

It says extra, don't add any more tags. Edit your M3U, create a fork and make with the correct M3U a pull-request. Sorry, don't have the time to edit the list now. I thank you. :-)

**Comment by Free-IPTV** [comment]
Where did you get this M3U from ???

There are other addresses in it than the original Pluto streams:

https://stream.oursnetworktv.com/latin/encoder29/playlist.m3u8 ???

The original Pluto streams ALL start with:

https: //service-stitcher.clusters.pluto.tv/stitch/hls/channel / ...
