### ISSUE TITLE
New Music Channels

### ISSUE THREAD

**Issue by Zhoro-111** [Free-IPTV/Countries#160]
Hi,I am new here and have no idea about how it works.I will post here the sources that I found if you can add them to music list....hope not wrong place.Peace!!

#EXTINF:-1 tvg-name="Muzzik TV Serbia" tvg-id="" group-title="MUSIK" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png",Muzzik TV Serbia
https://muzzik-live.morescreens.com/mts-6/playlist.m3u8
#EXTINF:-1 tvg-name="Muzzik Rock&Roll Serbia" tvg-id="" group-title="MUSIK" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png",Muzzik Rock&Roll Serbia
https://muzzik-live.morescreens.com/mts-1/playlist.m3u8
#EXTINF:-1 tvg-name="Muzzik Cafe&Club Serbia"" tvg-id="" group-title="MUSIK" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png",Muzzik Cafe&Club Serbia
https://muzzik-live.morescreens.com/mts-3/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik Worldwide Serbia" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik Worldwide Serbia
https://muzzik-live.morescreens.com/mts-5/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik Mediteraneo Serbia" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik Mediteraneo Serbia
https://muzzik-live.morescreens.com/mts-a5/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik HipHop Serbia" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik HipHop Serbia
https://muzzik-live.morescreens.com/mts-a4/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik Gen Z Serbia" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik Gen Z Serbia
https://muzzik-live.morescreens.com/mts-a2/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik AMVA 2020 Serbia" tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik AMVA 2020 Serbia
https://muzzik-live.morescreens.com/mts-8/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Muzzik OKK Serbia"  tvg-logo="https://www.muzzik.tv/wp-content/uploads/2019/05/muzzik-logo.png" group-title="MUSIK",Muzzik OKK Serbia
https://muzzik-live.morescreens.com/mts-2/playlist.m3u8

**Comment by CHJ85** [comment]
Great channels. I submitted a pull request for you.

**Comment by Free-IPTV** [comment]
Hi Zhoro-111,

all streams are GEO-BLOCKED from morescreens.com. Please only suggest streams that are not GEO-BLOCKED. I thank you.

**Comment by Free-IPTV** [comment]
Hi Zhoro-111 and CHJ85,

sorry, me again. My mistake, I tested the streams under VLC, because they were canceled. But they run in Kodi, strange. So all right, they come to the M3U for music. Sorry my mistakes!

**Comment by Zhoro-111** [comment]
There are 3 more channels in the list that you're missing (last 3 in the end)

**Comment by Free-IPTV** [comment]
Okay, sorry. I add the 3 streams in the next update. Thank you for your help! :-)

**Comment by Zhoro-111** [comment]
Can you check these channels ?


#EXTINF:-1 tvg-id="" tvg-name="Eurodance 90 HD" tvg-logo="https://www.coolstreaming.us/img/ch/image41813215893.jpg" group-title="MUSIK",Eurodance 90 HD
#EXTINF:-1 tvg-name="MUSIC +" tvg-id="" tvg-logo="https://onlinestream.live/logos/6465.png" group-title="MUSIK",MUSIC +
http://s02.diazol.hu:10192/hls/stream.m3u8
#EXTINF:-1 tvg-name="Muzsica Tv" tvg-id="" tvg-logo="https://onlinestream.live/logos/6151.png" group-title="MUSIK",Muzsica Tv
https://stream.y5.hu/stream/stream_muzsikatv/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="M3 Hungary" tvg-logo="https://onlinestream.live/logos/5931.png" group-title="HUNGARY",M3
https://streamjump2.mediaworld.gq/m3/0EjMxEjMyYjM.m3u8
#EXTINF:-1 tvg-id="" tvg-name="FILM +" tvg-logo="https://onlinestream.live/logos/6150.png" group-title="HUNGARY",FILM +
https://stream.y5.hu/stream/stream_filmp/hls1/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="RTL Club" tvg-logo="https://onlinestream.live/logos/6141.png" group-title="HUNGARY",RTL Club
https://stream.y5.hu/stream/stream_rtlklub/hls1/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="RTL2" tvg-logo="https://onlinestream.live/logos/6142.png" group-title="HUNGARY",RTL2
https://stream.y5.hu/stream/stream_rtl2/hls1/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="RTL Gold" tvg-logo="https://onlinestream.live/logos/5906.png" group-title="HUNGARY",RTL Gold
https://stream.y5.hu/stream/stream_rtlgold/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="RTL +" tvg-logo="https://onlinestream.live/logos/6147.png" group-title="HUNGARY",RTL +
https://stream.y5.hu/stream/stream_rtlp/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Cool TV" tvg-logo="https://onlinestream.live/logos/6146.png" group-title="HUNGARY",Cool TV
https://stream.y5.hu/stream/stream_cool/hls1/stream.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Series +" tvg-logo="https://onlinestream.live/logos/6149.png" group-title="HUNGARY",Series +
https://stream.y5.hu/stream/stream_sorozatp/stream.m3u8
#EXTINF:-1 tvg-name="ATV" tvg-id="" tvg-logo="https://onlinestream.live/logos/4739.png" group-title="HUNGARY",ATV
http://streamservers.atv.hu/atvlive/atvstream_1_aac/playlist.m3u8
#EXTINF:-1 tvg-name="Budapest Europe TV" tvg-id="" tvg-logo="https://onlinestream.live/logos/1819.png" group-title="HUNGARY",Budapest Europe TV
https://cloudfront44.lexanetwork.com:1344/freerelay/bpetv.sdp/playlist.m3u8

**Comment by Free-IPTV** [comment]
Hi @Zhoro-111 ,

1. I don´t know /catcast.tv, i think, it ist Pay-TV, there is a button to pay at the homepage.

2. MUSIC + (http://musicplus.hu) is okay, you can see the stream openly on the homepage.

3. The other streams is difficult to become information whether they are really free, for example:

https://en.wikipedia.org/wiki/Television_in_Hungary

4. ATV is okay!

5. Budapest Europe TV is geo-blocked.

I thank you but that cost me a lot of time now, I don't have that time. Please check beforehand whether they are freely available, it saves me a lot of time. ;-) In my YZ001_MUSIC there are many streams of Muzzik, they are all freely available, also on the homepage.

**Comment by Free-IPTV** [comment]
Next one...

Mediaworld.gq doesn't even have a homepage, there are probably servers somewhere abroad, doesn't seem serious or legal to me. 

The real streams from M (M1, M2 and so on) comes from connectmedia.hu. Look in my HU01_HUNGARY. ;-)

**Comment by Zhoro-111** [comment]
Sorry for that my friend, I am on my phone and it's hard to do what needed.

**Comment by Free-IPTV** [comment]
Okay, but for research you need a decent PC or notebook, with a smartphone it's just fiddly. ;-)
