### ISSUE TITLE
PlaylistEditorTV

### ISSUE THREAD

**Issue by vieirapedros** [Free-IPTV/Countries#164]
Hallo lieber Freund. Ich habe einige Nachforschungen angestellt und ein Programm gefunden, das uns helfen kann, "unsere" Liste zu verbessern.
Die Hauptfunktion besteht darin, nach doppelten oder nicht funktionierenden Kanälen zu suchen. Es ist auch möglich, Gruppen einfach zu bearbeiten.
Wenn Sie es versuchen möchten, finden Sie den Link hier: 

https://github.com/Isayso/PlaylistEditorTV

**Comment by Free-IPTV** [comment]
Hi @vieirapedros,

ich antworte einfach mal in deutsch. Ich hoffe, es wird richtig übersetzt. Ich benutze für das bearbeiten der einzelnen Listen Notepad++. Da ich mit Windows groß geworden bin, kenne ich leider absolut nichts von Linux. Für das prüfen auf Fehler und das Suchen nacht toten Links benutze ich den IPTV-Checker v2.5. 

In den Gruppen muss ich eh noch einiges ändern, mache ich diese Tage, z.B.:

1.  In jeder M3U oben in die erste Zeile eine Flagge und auch da die Gruppe reinsetzen, Beipiel:
      #EXTINF:-1 tvg-name="************** SWITZERLAND **********" group-title="SWITZERLAND" tvg-logo="https://i.imgur.com/eqVr8td.jpg",*************** SWITZERLAND **********
 
2.  Einheitlichkeit bei Gruppen mit 2 Namen, Beispiel Pluto, überall dann Land + Pluto, nicht PLUTO USA  

Es gibt noch viel zu tun. Es kam nun auch die HU01_HUNGARY und die MX01_MEXICO dazu. :-)

Liebe Grüße und ich danke dir. :-)

**Comment by vieirapedros** [comment]
Ich habe die gleichen Schwierigkeiten (ich weiß nur, wie man Windows und Office benutzt), also suche ich nach einem Programm, das helfen kann.
Ich habe andere Freeware gefunden, die Änderungen in großen Mengen und freundlicher vornehmen kann, was die Arbeit viel einfacher macht.
Zum Beispiel: https://www.tacoban.eu/m3ueditor/features.php

Ich bin bis April in einem professionellen Projekt. Danach verspreche ich, mehr Aufmerksamkeit zu schenken und mich der Hilfe für Sie zu widmen.

Große Umarmung

**Comment by Free-IPTV** [comment]
Ich danke dir! Momentan ist es ja eh gut, dass ich mit dem Projekt gut zu tun habe. Lass dir Zeit, Stress ist ungesund. ;-)
