### ISSUE TITLE
Fork from my Repo!

### ISSUE THREAD

**Issue by Free-IPTV** [Free-IPTV/Countries#165]
Hi @maggyskins,

you has create a forl from my repo. https://github.com/maggyskins/Countries

has you read my Readmy, the text regarding forks? If not, please read them carefully!

Would you like to contribute to my M3U?

If not, please remove the fork of my repo. Yesterday I changed my repo once, to private, that again to public, so that these unkempt and outdated forks at the top of my ad disappear.

Thank you!!!

https://www.vuplus-support.org/wbb4/index.php?thread/142192-astra-19-2e-settings-free-iptv-ipradio-ipwebcam/&postID=2081992#post2081992

https://www.vuplus-support.org/wbb4/index.php?thread/142192-astra-19-2e-settings-free-iptv-ipradio-ipwebcam/&postID=2081296#post2081296

and so on!!!

**Comment by Free-IPTV** [comment]
Hi @maggyskins,

okay, no answer is an answer. It's pretty much thirty-three to steal M3U's. to distinguish yourself and then ask for donations!

https://www.vuplus-support.org/wbb4/index.php?thread/142192-astra-19-2e-settings-free-iptv-ipradio-ipwebcam/

You can understand your drift here very well, in 2 forums, get information from Kodinerds, then repost M3U's in the other forum, NOT SO, YOU ARE BLOCKED:

https://www.vuplus-support.org/wbb4/index.php?thread/141764-iptv-free-web-tv-webcam-userbouquets/

https://www.kodinerds.net/index.php/Thread/71520-Weitere-freie-und-legale-Streams-f%C3%BCr-Kodi/?postID=627069#post627069

https://www.kodinerds.net/index.php/Thread/71520-Weitere-freie-und-legale-Streams-f%C3%BCr-Kodi/?postID=627224#post627224

Will still hear from me but NOT HERE!

**Comment by musuruan** [comment]
It seems that now I cannot no longer make pull request to your repo. Not so great! :-/

**Comment by Free-IPTV** [comment]
Hi  @musuruan,

you has an old Fork where i has deactivate for some times. **Delete the fork**:

forked from **smgrey/Countries**

**and make an new forl of my original master-repo:**

https://github.com/Free-IPTV/Countries

Then you can make a pull-request, thank you! :-)
