### ISSUE TITLE
I can't get anything from phone,nice list of music channels.

### ISSUE THREAD

**Issue by Zhoro-111** [Free-IPTV/Countries#166]
https://hqm.es/canales/

**Comment by Free-IPTV** [comment]
Hi @Zhoro-111 

okay, thank you. I can try to get some streams. :-)

**Comment by Free-IPTV** [comment]
I has got the stream "Relax" to test it.

Both streams not working in Kodi 18.9 and VLC-Player, sorry...

Stream Relax:

https://livelist01.yowi.tv/lista/dc1b71c6fda2e687050facaa7242062cbf5a7f2a/master.m3u8

https://livelist01.yowi.tv/lista/dc1b71c6fda2e687050facaa7242062cbf5a7f2a/index-f4-v1-a1.m3u8

**Comment by Free-IPTV** [comment]
In the streams is the domain yowi.tv

https://yowi.tv/

Some streams there works but not the HQM channels. Do you know, which country this ist? Spamin or Brazil?

**Comment by Zhoro-111** [comment]
On my phone all HQM channels on yowi works,I have no idea what country is.when I click the links you posted both working fine on browser but not on IPTV Smarters!!!
Take a look here https://yowi.tv.cutestat.com/

**Comment by Free-IPTV** [comment]
Yes. in the browser the stream works but not the links of these in a m3u...

https://livelist01.yowi.tv/lista/dc1b71c6fda2e687050facaa7242062cbf5a7f2a/master.m3u8

Only some tv streams (not HQM) from spain from the homepage yowi.tv works in a m3u. Tomorrow comes a new m3u: ES03_SPAIN_YOWITV ;-)

**Comment by Zhoro-111** [comment]
HQM are Spanish channels it seems,bad news they don't work on m3u.High quality ones :(

**Comment by Free-IPTV** [comment]
These channels comming tomorrow: TV Familia, TEF, DOTB, Lancelot TV, TV Extremena, 8 La Marina TV, Television de San Vicente, Hermes TV, Dejate de Historias, Imas TV, 3/24, TeleSur Madrid and TVL Teleganes.

They works fine in a m3u. :-)
