### ISSUE TITLE
??????

### ISSUE THREAD

**Issue by alexander-gricci** [Free-IPTV/Countries#179]
The playlist "Ukraine" contains the channels "Oplot" and "Oplot 2". These channels belong to the "DNR" organization. In accordance with the laws of Ukraine, this organization is classified as terrorist!

**Comment by Free-IPTV** [comment]
> 
> 
> The playlist "Ukraine" contains the channels "Oplot" and "Oplot 2". These channels belong to the "DNR" organization. In accordance with the laws of Ukraine, this organization is classified as terrorist!

Hi Alexander-Gricci,

we are absolutely impartial and apolitical when it comes to our streams. It's easy to just ask that we delete 2 streams.

Can you give me 2 new streams for Ukraine that we don't have in our UA01_UKRAINE yet ??? If we just delete it without thinking about it, our repo will soon be empty, think about it. ;-)

What are you doing for our repo? Now I'm curious. ;-)

**Comment by Free-IPTV** [comment]
@alexander-gricci 

a shame, no answer from you and I do NOT need such headlines! ISSUE CLOSED!
