### ISSUE TITLE
provide pak channels in this list plz

### ISSUE THREAD

**Issue by sultan-ayubi656** [Free-IPTV/Countries#186]

**Comment by Free-IPTV** [comment]
Hi sultan-ayubi656,

okay no problem. Can you give me some names of the tv stations that provide streams in Pakistan?

It will of course take a while until the new m3u is ready. When it goes online, I'll send you a message here. :-)

**Comment by Zhoro-111** [comment]
desiree.tv

> Hi sultan-ayubi656,
> 
> okay no problem. Can you give me some names of the tv stations that provide streams in Pakistan?
> 
> It will of course take a while until the new m3u is ready. When it goes online, I'll send you a message here. :-)

https://www.desiree.tv

**Comment by Free-IPTV** [comment]
Hi @Zhoro-111 

i has the first streams ready... you can look at other streams, the PK01_PAKISTAN is created, lokal in my notebook. These streams i have: 92 News, ARY News, Avt Khyber, Dunya News, Kay2 TV, Khyber Middle East, Khyber News, Minhaj TV, PTV Sports, Zindagi TV

I make the upload tomorrow morning and the you can add your channels, okay? Teamwork. :-)

**Comment by Free-IPTV** [comment]
Hi @Zhoro-111 ,

i make now the upload und you can add the streams where you fond, ist better. :-)

**Comment by Zhoro-111** [comment]
> Hi @Zhoro-111 ,
> 
> i make now the upload und you can add the streams where you found, it´s better. :-)

Can't get 8XM to work !!

**Comment by Free-IPTV** [comment]
> 
> 
> > Hi @Zhoro-111 ,
> > i make now the upload und you can add the streams where you found, it´s better. :-)
> 
> Can't get 8XM to work !!can't do much from phone.

8XM and some others you can forget, they use Auth=. Streams with token and etc. doesn´t work for a long time in m3u. I make now your pull-request, i cahnge some streams to .playlist. m3u and add also some new streams. Thnak you for your great help and... you need a notebook! ;-)
