### ISSUE TITLE
Fix FOX TV on TR01_TURKEY.m3u

### ISSUE THREAD

**Issue by iCloExecutable** [Free-IPTV/Countries#203]
so when i try opening fox tv on vlc it sends a error

the error is : vlc, 'https://foxtv.daioncdn.net/foxtv/foxtv_360p.m3u8?ex=1615587198&st=1QlfpmlicmPXLfZEnv806A&sid=37n3ufcn9mtq&app=24e7a2e2-9156-4c02-a4fb-2bc599ffaf77&ce=3" unable to open media source address (MRL). Check the log file for details.

**Comment by Free-IPTV** [comment]
Hi @iCloExecutable

in the next update, this stream is removed. sid= don´t work for a long time.

**Comment by iCloExecutable** [comment]
> 
> 
> Hi @iCloExecutable
> 
> in the next update, this stream is removed. sid= don´t work for a long time. Thanks for reporting it. :-)

ok so privately i got it working
