### ISSUE TITLE
Content removed! You are blocked!!!

### ISSUE THREAD

**Issue by sharifAhmed87** [Free-IPTV/Countries#209]
Content removed! You are blocked!!!

**Comment by Free-IPTV** [comment]
Hi @sharifAhmed87

sorry, in the US01_USA are no channels with name "Cinemax". I have only m3u in my Repo, no EGP-Files. 

If you mean another m3u, you have to tell me the exact name. I don't know every single stream here and we now offer OVER 3500 legal and free streams. More than 80 M3U´s! I thank you. :-)
