### ISSUE TITLE
USA Stream The Weather Channel Dead

### ISSUE THREAD

**Issue by floydcg** [Free-IPTV/Countries#215]
Looks like the stream address for the weather channel has changed. They still have a valid stream still that can be accessed through any of their apps so it might just need to be extracted from that

**Comment by Free-IPTV** [comment]
Hi @floydcg,

at the moment i has only the streams for Weathernation and Weatherspy. As soon as I have a working legal stream it comes into the m3u. I thank you.

**Comment by Free-IPTV** [comment]
Hi @floydcg,

i never give up... Haha, there is a legal and free stream! Tomorrow morning i make the next updates, then is the working address in the US01:USA:

https://weather-lh.akamaihd.net/i/twc_1@92006/index_1200_av-p.m3u8?sd=10&rebase=on
