### ISSUE TITLE
Two free national channel of Italy television.

### ISSUE THREAD

**Issue by infid0** [Free-IPTV/Countries#229]
**Channel:** Tv8
**Site:** https://tv8.it/streaming.html
**Stream:** https://skyanywhere3-i.akamaihd.net/hls/live/510694/mtv8sdlive/index.m3u8

**Channel:** Cielo
**Site:** https://www.cielotv.it/streaming.html
**Stream:** https://skyanywhere3-i.akamaihd.net/hls/live/510693/cielo/playlist.m3u8

_Thank you!_

**Comment by Free-IPTV** [comment]
Hi @infid0,

thank you for your help. TV8 are not working, also not on homepage. Can be, this stream is geo-blocked.

Cielo also not working and when i call the hompage, there comes a security warning from my browser!

Please only give tips for streams, when they are working ant the hompages are okay. ;-)

**Comment by infid0** [comment]
Hi, please i'm so sorry! These streams has ever works fine and not has never changed. But now works only with other "extra parts" of link. Example: 
https://skyanywhere3-i.akamaihd.net/hls/live/510694/mtv8sdlive/index.m3u8?hdnea=st=1616594072~exp=1616594372~acl=/*~hmac=58c1d171a8e7b811b696a41771c0efe7e3537d9542dfb977ca5d8a3f62b1155d
But i think these "extra parts" change every day. 😞 
Thank you anyway and sorry again!
