### ISSUE TITLE
Problem with accented letters: "ICI TÃ©lÃ© HD" should be "ICI Télé HD" or at least "ICI Tele HD"

### ISSUE THREAD

**Issue by SebastJava** [Free-IPTV/Countries#23]
There is a problem with accented letters when displaying some French-Canadian IPTV names from your list on the new (alpha version!) Hypnotix (https://github.com/linuxmint/hypnotix)

In this file:
https://github.com/Free-IPTV/Countries/blob/master/ZZ_PLAYLIST_ALL_TV.m3u
Lines 1840-1841:
```
#EXTINF:-1 tvg-name="ICI TÃ©lÃ© HD" tvg-id="ICI TÃ©lÃ© HD" group-title="CANADA" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Current_Logo_of_Ici_Radio-Canada_T%C3%A9l%C3%A9_%282016-present%29.svg/300px-Current_Logo_of_Ici_Radio-Canada_T%C3%A9l%C3%A9_%282016-present%29.svg.png",ICI TÃ©lÃ© HD
https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master_2500.m3u8
```
Problem with accented letters:
`tvg-name="ICI TÃ©lÃ© HD"`
should be replaced with:
`tvg-name="ICI Télé HD"` -OR- `tvg-name="ICI Tele HD"`

I guess accented letters are not possible, so, to be safe, i would re-edit lines 1840-1841 as this:
```
#EXTINF:-1 tvg-name="ICI Tele HD" tvg-id="ICI Tele HD" group-title="CANADA" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/c/cf/Current_Logo_of_Ici_Radio-Canada_T%C3%A9l%C3%A9_%282016-present%29.svg/300px-Current_Logo_of_Ici_Radio-Canada_T%C3%A9l%C3%A9_%282016-present%29.svg.png",ICI Tele HD
https://rcavlive.akamaized.net/hls/live/696615/xcancbft/master_2500.m3u8
```
Well, maybe not? Maybe the problem comes from https://github.com/linuxmint/hypnotix... I don’t know.
![Screenshot from 2020-11-27 21-05-40](https://user-images.githubusercontent.com/31940713/100491916-99c6de80-30f5-11eb-9893-0e00e9a31ff5.png)

**Comment by Free-IPTV** [comment]
Hi,

thank you for your information, i has correct this. :-)

Greetings

**Comment by SebastJava** [comment]
Hi @Free-IPTV 

Sorry to bother you with this again, but i saw some Belgium TV names with accented letters. They are displayed correctly on your list here and on Hypnotix.

So could you please change "ICI Tele HD" to "ICI Télé HD" ? Thanks.

That’s no big deal, i am just being perfectionist. :)

**Comment by Free-IPTV** [comment]
Hi SebastJave,

Okay, I changed it to ICI Télé HD, now it stays that way. In the file for Belgium i has also change Télé . The files saved in UTF8. The name is clearly displayed in the IPTV single client (Kodi) for me. nobody is perfect! ;-)

**Comment by SebastJava** [comment]
Hi @Free-IPTV 

First of all, thanks for those quick responses. I am sorry to bother you again. The problem got worst! Now the names with accented letters look very bad ("ICI TÃ©lÃ© HD") in both Canada and Belgium listings. See my 2 screenshots down here.

Don’t panic! It looks like everything is fine in both https://github.com/Free-IPTV/Countries/blob/master/BE01_BELGIUM.m3u and https://github.com/Free-IPTV/Countries/blob/master/CA01_CANADA.m3u. But Hypnotix is using https://github.com/Free-IPTV/Countries/blob/master/ZZ_PLAYLIST_ALL_TV.m3u and i see things got worst there.

Maybe you could download this new, alpha version Hypnotix and see by yourself? Here: http://linuxmint.com/tmp/blog/3978/hypnotix_1.0.0_all.deb This would solve our "feedback loop".

UTF-8 ? This looks good. I guess you just need to transfer these updates from BE01_BELGIUM and CA01_CANADA to  ZZ_PLAYLIST_ALL_TV:

BE01_BELGIUM ->  ZZ_PLAYLIST_ALL_TV
CA01_CANADA -> ZZ_PLAYLIST_ALL_TV

Thanks again!

![Hypnotix-Canada](https://user-images.githubusercontent.com/31940713/100551047-5fbc2080-324c-11eb-8e36-a29e9347dd42.png)
![Hypnotix-Belgium](https://user-images.githubusercontent.com/31940713/100551049-6054b700-324c-11eb-819a-9d9161e44080.png)

**Comment by SebastJava** [comment]
Hey, i suggest you do this quick test: search for "©" in ZZ_PLAYLIST_ALL_TV. There are 25 of them... There should be none, except this "© 2020 GitHub, Inc." at the bottom of the page... :)

**Comment by SebastJava** [comment]
@Free-IPTV 

To make it clearer and simpler:
1. In https://github.com/Free-IPTV/Countries/blob/master/ZZ_PLAYLIST_ALL_TV.m3u
2. Auto Find & Replace all "Ã©" -> "é"
3. Then save in UTF-8, add-commit-push, and, if possible, check in Hypnotix.

Thanks.
P.S.: I did not see any other problem, but lets do some prevention. There could also be problems with "é,è,ê,î,â,ö" and "É,È,Ê,Î,Â,Ö". You could check ALL these using this: https://www.i18nqa.com/debug/utf8-debug.html Or else, just wait for people like me to open an issue for each little weird character. But don’t panic, "é" are the most common and i only found a few of them... 24, to be precise.

**Comment by Free-IPTV** [comment]
Hi Sebastian,

the ZZ_PLAYLIST_ALL_TV.m3u is automatically created from the individual files. For this I use the ADDON IPTV-Merge from Matt Husiman (NZ).

So the problem is the ADDON and not the individual files (Canada and Belgium). Take a look at the file for Belgium:

https://github.com/Free-IPTV/Countries/blob/master/BE01_BELGIUM.m3u

it is correct there! I edit all files with Notepad ++ and they are all saved in UTF8 format.

It's already enough work, I will not edit the ZZ_PLAYLIST_ALL_TV playlist by hand now.

So I am changing that to a simple "e" that everyone around the world recognizes as "e".  I am changing this for the last time in the file for Belgium and Canada.

Sorry but I am NOT a perfectionist and my lists have to be readable for everyone and work in every country!

**Comment by SebastJava** [comment]
Hi @Free-IPTV 

Okay. I understand you are overloaded. I am not asking for any more work. Just making diplomacy adjustments here.

1. I knew things were okay in your individual files and the problem was only with the ZZ_PLAYLIST_ALL_TV. I did point this out before.
2. When saying i was a perfectionist, i did not mean to be aggressive in anyway, i was saying that i was caring for some little details and thus admitting it was not so important.
3. You are saying "my lists have to be readable for everyone and work in every country!" That’s what UTF-8 is there for! If you see "Télé" printed correctly here on GitHub in your browser, it will also print correctly on Hypnotix, or any other modern software, everywhere in the world. As far as i know. I can’t be absolutely sure, but i think UTF-8 is pretty universal.

But changing from "ICI TÃ©lÃ© HD" to "ICI Tele HD" is quite an improvement. That will do.

**Joyeux Noël! Fröhliche Weihnachten!**
(UTF-8 and https://translate.google.ca)

**Comment by Free-IPTV** [comment]
Hi Sebastien,

OK. The problem is the IPTV-Merge add-on. With that the ZZ_PLAYLIST_ALL_TV.m3u created in Kodi, which then comes on Github. The addon has problems creating the playlist with the "é, è, ê, î, â, ö" and "É, È, Ê, Î, Â, Ö".

Many greetings and also Fröhliche Weihnachten. :-)
