### ISSUE TITLE
Paramount Network Italy

### ISSUE THREAD

**Issue by infid0** [Free-IPTV/Countries#230]
Paramount Network is a free national channel of the italian DVB-T.

**Channel:** Paramount Network
**Site:** https://www.paramountnetwork.it/diretta-tv/wp5pr2
**Stream:** https://viacomitalytest-lh.akamaihd.net/i/sbshdlive_1@195657/master.m3u8

_P.S. Maybe is geo-blocked, but i've tested this stream on (my) VLC and work fine. Thank you._

**Comment by Zhoro-111** [comment]
It's geo-blocked,you must use a VPN and pick a server outside Italy to test it.
