### ISSUE TITLE
San Marino RTV

### ISSUE THREAD

**Issue by fparri** [Free-IPTV/Countries#233]
Free streams without geoblock of the Republica of San Marino's state TV and radio channels can be found on the official web site:

https://www.sanmarinortv.sm/programmi/web-tv

Would it be possibile to add them?

**Comment by Zhoro-111** [comment]
San Marino RTV and RTV Sport are on ITALIA list.

**Comment by Free-IPTV** [comment]
Hi @fparri,

today are comming new streams to the IT01_ITALY:

Amuse Animation, Atres Series, Bizzarro Movies, Brindiamo Channel, Cinema Segreto, Classical Harmony and Duck TV

All streams are free and legal, they are comming from wurl.com. :-)
