### ISSUE TITLE
Channel sorted in wrong country (CNA 24/7)

### ISSUE THREAD

**Issue by tsr** [Free-IPTV/Countries#24]
https://github.com/Free-IPTV/Countries/blob/405a1226df29d0f45601e3f589f2b9389a7b23d7/JP01_JAPAN.m3u#L8

Hi,

the channel CNA 24/7 is not Japanese, but Singaporean. :)
https://en.wikipedia.org/wiki/CNA_(TV_network)

So a new category is needed.

**Comment by Free-IPTV** [comment]
Hi Sascha,

okay, thanks for your important Info. To,orrow ich create the new file SG01_SINGAPORE.M3U and i move CNA 24/7 to it. I will then continue searching for streams for the new file and then publish it.

Best regards :-)

**Comment by Free-IPTV** [comment]
Hi Sascha,

so, die neue M3U SG01 ist da. Leider gibt es da momentan nur einen Stream. 

Grüße
