### ISSUE TITLE
new channel in Israel

### ISSUE THREAD

**Issue by adinaveh** [Free-IPTV/Countries#251]
Jesus Shelanu
 - Link removed, before it is stolen again by other incompetent - Haha

**Comment by Free-IPTV** [comment]
Hi @adinaveh,

thank you for this stream. I saved it! Too many steal our work and publish it elsewhere as YOUR work.  There will be a change, after that everyone can access our m3u's again. Haha ... but then the guys from IPTV-ORG and others can no longer copy our work all the time. You can find the information here in my readme after the changes! :-)

**Comment by adinaveh** [comment]
where do you prefer that I will send you other channels?

**Comment by adinaveh** [comment]
where do you prefer that I will send you other channels?

**Comment by Free-IPTV** [comment]
> 
> 
> where do you prefer that I will send you other channels?

When I make the change, the readme says how to proceed in order to have access to the new repo!!! Just pay attention to the update of the readme. ;-)

**Comment by Free-IPTV** [comment]
> 
> 
> where do you prefer that I will send you other channels?

Read my Readme, there is a description of the new (private) repo. :-)

https://github.com/Free-IPTV/Countries/blob/master/README.md
