### ISSUE TITLE
Honest user... Repo request 

### ISSUE THREAD

**Issue by Nandolara80** [Free-IPTV/Countries#254]
Hi, I'm interested in accessing to thr private repo, I know... I'm new in Github.com but I'm an honest user.

best regards

**Comment by UsernameGi** [comment]
Me too and i am requesting a repo and hope do your best work.

**Comment by bernie1968** [comment]
Hi, can I have the new private repo? Keep up the good work!!

**Comment by Free-IPTV** [comment]
Hi @bernie1968,

please no post overall. ;-) I has answered for you in another issue. The 2 others... sorry, at the moment NOW new users, Read the README!

**Comment by UsernameGi** [comment]
i did read the readme i know it says New users who recently created an account on Github in the readme please give me the private repo

**Comment by UsernameGi** [comment]
and i dont have an old account too this is only one account i have

**Comment by Free-IPTV** [comment]
> 
> 
> and i dont have an old account too this is only one account i have

Sorry, i don't know you, some of these crooks will now try to get in here. Nothing against you but how can you convince me that you only want to use my m3u's privately?

Do you have a reference, a user who has been here on Github for a long time? Maybe you have a homepage where you can get more information?

**Comment by UsernameGi** [comment]
i want to watch tv channels on hypnotix on linux mint just please give me the repo

**Comment by UsernameGi** [comment]
then i can watch tv channels thats all i want

**Comment by Free-IPTV** [comment]
Hypnotix will continue to have access. I wrote to them in their repo a few days ago, but nobody answers. The new access must urgently be clarified. Hypnotix will then still be able to use our m3u's.

https://github.com/linuxmint/hypnotix/issues/124

**Comment by UsernameGi** [comment]
i already read that one day ago

**Comment by UsernameGi** [comment]
what if i want it now

**Comment by UsernameGi** [comment]
how old is a github account do you need to access the repo

**Comment by Free-IPTV** [comment]
We haven't clarified yet, due to the previous situation we are more cautious now. sorry, there is no other way

For Hypnotix you don´t need a account, read above! Thank you!

**Comment by UsernameGi** [comment]
at least i can still use the channels the old ZZ_PLAYLIST_ALL_TV.m3u when didnt delete lots of channels

**Comment by UsernameGi** [comment]
and still have 3684 tv channels

**Comment by UsernameGi** [comment]
and have a good day too

**Comment by Free-IPTV** [comment]
Okay, also. Read the issue at Repo of the Hypnotix App, ther is talking about access for Hypnotix-User. ;-)

https://github.com/linuxmint/hypnotix/

**Comment by brainboyusa** [comment]
Good afternoon. I have been using the M3U lines for personal use only, I not even had an account here until today. I don't really understand how these things work but I understand that only users already registered this all happened, will have access to the repo. It's really a shame that because of some stupid dishonest brat, honest users like me will lose access to the great list of legal channels. I completely understand your frustration, however, I'd really appreciate to be considered as a new member in case you would give me the opportunity. Many thanks.

**Comment by Free-IPTV** [comment]
Hi @brainboyusa,

Sorry, I don't feel like it anymore. Since this agitation against me is also starting here at Github, a limit has now been crossed. Thank you silly idiots who didn't get what happened so far:

https://github.com/linuxmint/hypnotix/issues/124#issuecomment-817116183
