### ISSUE TITLE
Requesting invite to the private repo

### ISSUE THREAD

**Issue by inuboshi** [Free-IPTV/Countries#256]
title.

**Comment by leonardoivo** [comment]
Dear,
   I am user the list, also here contribuir para essa lista. Antes mesmo desse incidente eu estava querem passar mais sugestões de novos canais. Gostaria de ter acesso a essa nova lista e poder contribuir com ou sem acesso a ela. Obrigado desde já.
   Atenciosamente,

**Comment by leonardoivo** [comment]
I would like to say that I will follow all the conditions established by you.

**Comment by bernie1968** [comment]
Hi, can i have the new private repo? I really like the updates and keep up the good work!!!

**Comment by Free-IPTV** [comment]
Hi @leonardoivo and @bernie1968 ,

i has answered in another issue! Thank  you.
