### ISSUE TITLE
access to private repo

### ISSUE THREAD

**Issue by TheBrit007** [Free-IPTV/Countries#258]
Id like to receive access to private repo.  Im new to registration on github because I try not to register on websites but have been a user for awhile and have donated to you and other creators on the site in the past.  I will gladly help when I can to help grow the list of public content

**Comment by Free-IPTV** [comment]
You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations.

**Comment by pippolive** [comment]
Hallo, ich habe bereits gespendet.
Sie haben 10,00 EUR an Free-IPTV gesendet
IHRE MITTEILUNG AN Free-IPTV
Wünderbare Arbeit geleistet

pippolive

**Comment by Free-IPTV** [comment]
Hi @pippolive,

YES, now I can assign it.! Now you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

Thank you!!! :-)

**Comment by TheBrit007** [comment]
> You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?

i have donated thru paypal, how can i message you the email of the latest donation

**Comment by Free-IPTV** [comment]
> 
> 
> > You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible
> 
> i have donated thru paypal, how can i message you the email of the latest donation

We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)

**Comment by TheBrit007** [comment]
> > > You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible
> > 
> > 
> > i have donated thru paypal, how can i message you the email of the latest donation
> 
> We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)

first one was $5 in January, US, another in February, and another yesterday $5 US.  i dont remember exact dates for January and February

**Comment by Free-IPTV** [comment]
> 
> 
> > > > You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible
> > > 
> > > 
> > > i have donated thru paypal, how can i message you the email of the latest donation
> > 
> > 
> > We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)
> 
> first one was $5 in January, US, another in February, and another yesterday $5 US. i dont remember exact dates for January and February

**Sorry, in January here was still no link for PayPal!** In March ONLY one donation was in $ with MORE than $5, the other donations were in EUR. The amounts donated also differ from the $ 5 amount. **I think that donated to someone else.** Your details do NOT match to my donations.

**Comment by TheBrit007** [comment]
> > > > > You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible
> > > > 
> > > > 
> > > > i have donated thru paypal, how can i message you the email of the latest donation
> > > 
> > > 
> > > We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)
> > 
> > 
> > first one was $5 in January, US, another in February, and another yesterday $5 US. i dont remember exact dates for January and February
> 
> **Sorry, in January here was still no link for PayPal!** In March ONLY one donation was in $ with MORE than $5, the other donations were in EUR. The amounts donated also differ from the $ 5 amount. **I think that donated to someone else.** Your details do NOT match to my donations.


Payment to Free-IPTVCompleted | -€4.08 EUR
-- | --


that is the one from yesterday, i will need to research the others. but i dont mind donating larger amounts periodically as im using it and it helps support the project

**Comment by pippolive** [comment]
Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: TheBrit007 ***@***.***>Datum: Mo., 5. Apr. 2021, 13:56An: Free-IPTV/Countries ***@***.***>Cc: pippolive ***@***.***>, Mention ***@***.***>Betreff: Re: [Free-IPTV/Countries] access to private repo (#258)











You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donations. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible



i have donated thru paypal, how can i message you the email of the latest donation



We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)



first one was $5 in January, US, another in February, and another yesterday $5 US. i dont remember exact dates for January and February



Sorry, in January here was still no link for PayPal! In March ONLY one donation was in $ with MORE than $5, the other donations were in EUR. The amounts donated also differ from the $ 5 amount. I think that donated to someone else. Your details do NOT match to my donations.



Payment to Free-IPTVCompleted-€4.08 EUR

that is the one from yesterday, i will need to research the others. but i dont mind donating larger amounts periodically as im using it and it helps support the project

**Comment by Free-IPTV** [comment]
> 
> 
> > > > > > You are a new user. Have you already donated for us? Then I need the name of the donation because your username (Github) does not appear in the donation
> Payment to Free-IPTVCompleted 	-s. On which day (complete date) has you make the donation?  I am a new user only because I do not want to lose out on your service, i prefer not to register on sites if possible
> > > > > 
> > > > > 
> > > > > i have donated thru paypal, how can i message you the email of the latest donation
> > > > 
> > > > 
> > > > We don't need an email. Just tell me the day, the amount and the country, where you has paid. :-) Then I can assign it, thank you. :-)
> > > 
> > > 
> > > first one was $5 in January, US, another in February, and another yesterday $5 US. i dont remember exact dates for January and February
> > 
> > 
> > **Sorry, in January here was still no link for PayPal!** In March ONLY one donation was in $ with MORE than $5, the other donations were in EUR. The amounts donated also differ from the $ 5 amount. **I think that donated to someone else.** Your details do NOT match to my donations.
> 
> Payment to Free-IPTVCompleted 	-€4.08 EUR
> 
> that is the one from yesterday, i will need to research the others. but i dont mind donating larger amounts periodically as im using it and it helps support the project

This is okay! You has wrote $5... haha... YES yesterday ther was €4.08 EUR!!! you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by Free-IPTV** [comment]
> 
> Payment to Free-IPTVCompleted 	-€4.08 EUR
> 
> that is the one from yesterday, i will need to research the others. but i dont mind donating larger amounts periodically as im using it and it helps support the project

This is okay! You has wrote $5... haha... YES yesterday ther was €4.08 EUR!!! you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by Free-IPTV** [comment]
@pippolive ,

i has send you an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:

https://github.com/Free-IPTV

**Comment by TheBrit007** [comment]
> > Payment to Free-IPTVCompleted 	-€4.08 EUR
> > that is the one from yesterday, i will need to research the others. but i dont mind donating larger amounts periodically as im using it and it helps support the project
> 
> This is okay! You has wrote $5... haha... YES yesterday ther was €4.08 EUR!!! you will receive an invitation with access from the new repo (PRIVATE). Only users with authorized access will then see the new repo here:
> 
> https://github.com/Free-IPTV

Lol, I forgot about the euro conversation.  I appreciate  you giving me access

**Comment by Free-IPTV** [comment]
Hi @all

**The donations should be an appreciation of our work. They are in NO connection to the free streams or access to the PRIVATE repo!**
