### ISSUE TITLE
Japan: Netchannel KYO no longer works

### ISSUE THREAD

**Issue by ShapeShifter499** [Free-IPTV/Countries#26]
When attempting to load this in Kodi I get an error message from the Youtube plugin.  "This video has been removed by the uploader"

I don't know if there is another source for this channel but the one included in the 
ZZ_PLAYLIST_ALL_TV.m3u file does not work.

**Comment by ShapeShifter499** [comment]
Would this link be a updated and correct place for this channel?  I can't be sure because I haven't heard of Netchannel KYO before

https://www.youtube.com/watch?v=hU9Z1nAN7YQ

**Comment by Free-IPTV** [comment]
Hi ShapeShifter499 

thanks for your help! I has correct this in the JP01_JAPAN.m3u. The ZZ_PLAYLIST_ALL_TV.m3u is created automaticely with an Kodi-Addon. This file i do not edit. I make in few minutes a new upload!

Regards! :-)
