### ISSUE TITLE
Access to private Repo

### ISSUE THREAD

**Issue by uglymusician** [Free-IPTV/Countries#260]
Hi, i would like to access the private repo if possible. I know my account is new, I have never used Github before. If it would help to verify my intentions I would gladly make a donation to your project, just tell me how much you would require. I'm strictly a private user on the hypnotix app.

Thank you in advance :)

**Comment by Free-IPTV** [comment]
Sorry, i don't know you, some of these crooks will now try to get in here. Nothing against you but how can you convince me that you only want to use my m3u's privately?

Do you have a reference, a user who has been here on Github for a long time? Maybe you have a homepage where you can get more information?

**Comment by Free-IPTV** [comment]
Hypnotix will continue to have access. I wrote to them in their repo a few days ago, but nobody answers. The new access must urgently be clarified. Hypnotix will then still be able to use our m3u's.

Look there: linuxmint/hypnotix#124

**Comment by UsernameGi** [comment]
same as me

**Comment by Free-IPTV** [comment]
> 
> 
> same as me

Read the ISSUE at the repo of Hypnotics, there we are talking about this!
