### ISSUE TITLE
Action Request

### ISSUE THREAD

**Issue by petra1000** [Free-IPTV/Countries#272]
hello,

**Comment by Free-IPTV** [comment]
> 
> 
> hello,
> 
> I would like to access the new repo
> 
> I sent you 3.26 Eur On 4/5
> 
> My is is petra1000

DONT send anything!!! Please read the readme. Please read carefully! Thank you!

https://github.com/Free-IPTV/Countries/blob/master/README.md

**Comment by Free-IPTV** [comment]
Hi @petra1000,

First you annoy here without end, then you continue via email! Who so penetrating over several days by email nervt, comes NOT in the new private repo. Change your behavior!
