### ISSUE TITLE
Hi there 

### ISSUE THREAD

**Issue by waltvm** [Free-IPTV/Countries#273]
I’m walter from Belgium. I would like to have access to your m3u
I just learned about m3u files and was using tivimate on my Nvidia shield, 
Your list was the best . 
I read you do not allow new profiles to your list. But as a sign of trust I give you my phone number and LinkedIn profile. Do call me , no problem

**Comment by Free-IPTV** [comment]
Hi @waltvm,

i has edit (remove) your data because anybody can read this. Thanks for you trust but the problem is, your account is created yesterday. At the moment we can´t accept User with new account. 

Please don´t post private data here. ;-)

**Comment by waltvm** [comment]
Hi, 

Can you tell me why you don’t accept new users? 
Maybe we can find a solution? 


Met vriendelijke groeten,
Walter Van Mieghem
0477 75 55 30
