### ISSUE TITLE
Private repo access

### ISSUE THREAD

**Issue by jakoblm** [Free-IPTV/Countries#274]
Hello, I would be interested in accessing the private repo. I hope this is the right place to contact. At this point a big thank you for all the work you put into the project.

**Comment by Free-IPTV** [comment]
Hi @jakoblm,

you are using the Hypnotix APP? For the Linux Mint team there would be a another solution next time. 

Look at the Hypnotix Repo in ISSUES

**Comment by jakoblm** [comment]
Why was my request closed without comment? You wrote that users can contact you via the Issues menu.

**Comment by Free-IPTV** [comment]
For Hypnotix User there is another solution. Look there is an issue Free-IPTV!

https://github.com/linuxmint/hypnotix

**Comment by jakoblm** [comment]
Yes, I use Hypnotix. Would be happy about a solution for this. 
Sorry, had not read your first message.
