### ISSUE TITLE
Hello Again

### ISSUE THREAD

**Issue by petra1000** [Free-IPTV/Countries#276]
hello,

THE FOLLOWING RULES FOR THE NEW PRIVATE REPO MUST BE OBSERVED:

    ONLY CREATE A FORK IF YOU WANT TO WORK WITH ME 
I will If I ever decide to create a fork

    A FORK MAY ONLY BE CREATED, IF THEN THERE ALSO COMES A PULL REQUEST
I understand will do this

    ALL M3Us ARE INTENDED FOR PRIVATE USE ONLY!!!
I agree 100% This would be used in my house only
    IT IS NOT ALLOWED TO SEND ME ILLGEGAL STREAMS VIA PULL REQUEST OR POST PER ISSUE
I fully understand and agree to this
    USE FOR COMMERCIAL PURPOSES IS NOT PERMITTED
I agree 120% to this
    DISTRIBUTING OR POSTING MY LISTS IN GITHUB, FORUMS, HOMEPAGES OR IN SOCIAL NETWORKS IS NOT PERMITTED
    WHO BREACHES THESE RULES, FLY OUT OF THE PRIVATE IMMEDIATELY
I full understand

WHO DOESN'T COME TO THE NEW PRIVATE REPO

    Contributors and Users (Issues) from IPTV-ORG - I have no issues
    Blocked users - was never blocked
    New users who recently created an account on Github
I signup up with Github on 4/5 because I am not a programmer and I never saw a need for Github until 4/5. I have enjoyed your list in my home. I also donated yesterday because I finally saw where I can donate. I know It takes a lot of time to do what you do and thank you for all your hard work. I fully understand that this is for private use only. I have been using kodi and m3u lists for about 3 to 4 years. When I came across your list I was very happy to a list of free streams.

So please allow me to come to your private repo.  If not that is still ok. 

Thank You

petra1000

**Comment by Free-IPTV** [comment]
Hi @petra1000,

you has wrote:

_I sent you 3.26 Eur On 4/5_

sorry, On May 4th no donation was received from 3.26 Eur! Maybe you made a mistake. ;-)

Please give me that Transactioncode!

Since we had an incident in the new private repo yesterday anyway, recordings of users with new accounts are stopped anyway. Please read this:

https://github.com/Free-IPTV/Countries/issues/275#issuecomment-813930589

**Comment by Zhoro-111** [comment]
> Hi @petra1000,
> 
> you has wrote:
> 
> _I sent you 3.26 Eur On 4/5_
> 
> sorry, On May 4th no donation was received from 3.26 Eur! Maybe you made a mistake. ;-)
> 
> Please give me that Transactioncode!
> 
> Since we had an incident in the new private repo yesterday anyway, recordings of users with new accounts are stopped anyway. Please read this:
> 
> [#275 (comment)](https://github.com/Free-IPTV/Countries/issues/275#issuecomment-813930589)

https://github.com/Free-IPTV/Countries/issues/275#issuecomment-814354449
