### ISSUE TITLE
Hypnotix on Alpine Linux

### ISSUE THREAD

**Issue by antonialoytorrens** [Free-IPTV/Countries#277]
Hello all,
I'm the maintainer of the Hypnotix app in Alpine Linux.
I don't know if it's correct to make an issue here, because I don't know if I could update this app anymore or remove it from aports repository because your Readme says that only Linux Mint team has access via Hypnotix app.

So, as this repository is private now and your license has changed, I'd like to request access to use this app in Alpine Linux distribution, with your Free-IPTV service provider by default.

Thank you in advance. Otherwise, I will kindly remove it from aports repository or patch it to remove your services if there is some conflict about it.

**Comment by Free-IPTV** [comment]
Hi @antonialoytorrens 

sorry, here is no Hypnotix Support please tage the menu issues ther, thank you:

https://github.com/linuxmint/hypnotix

**Comment by antonialoytorrens** [comment]
> Hi @antonialoytorrens
> 
> sorry, here is no Hypnotix Support please take the menu issues there, thank you:
> 
> https://github.com/linuxmint/hypnotix
> 
> I am in contact with the Linux Mint team for a new solution. Here i can´t help!

Thank you very much!
