### ISSUE TITLE
Donation /  Id. de transacción: 8SL18837A2229343K

### ISSUE THREAD

**Issue by rduetsch** [Free-IPTV/Countries#279]
Hello 

I am not shure if you recieved my donation? did not had a confirmation from your side.

Thank you 

PS: habe eine frage die ich liebver auf deutsch stelle ich habe gesehen das iptv-org von meinen fork von Euch auch einen fork gemacht hat bei meinem account sollte ich das blockieren?

![image](https://user-images.githubusercontent.com/25334712/113765133-2cb6fb80-971c-11eb-84f1-09a1b6a552ad.png)

**Comment by Free-IPTV** [comment]
Hi @rduetsch,

Einladung ist schon lange raus, siehe Foto!

Was das Fork betrifft, da hast du ein Fork vom Master Repo von IPTV-ORG erstellt. Was willst du damit. Ist eh ein Drecksladen, viele illegale Streams und besonder der Contributor Ghost hat kriminelles Potenzial. Habe da als Issue im privateh Repo gepostet, wegen dem Manipulationsversuch des User Ghost . Lösche doch einfach das Fork von IPTV-ORG. 

Danke für die Spende!!!!

![rduetsch](https://user-images.githubusercontent.com/45691270/113820555-273cce00-977b-11eb-9a68-32f3348de891.jpg)

**Comment by rduetsch** [comment]
Hallo nochmals.... unglücklicherweise finde ich deine Einladung nicht um Sie zu bestätigen wo kann ich das tun?
entschuldige die umstände....thx

**Comment by rduetsch** [comment]
danke.... um stream updates zu machen soll ich auch ein fork machen oder besser nicht?

**Comment by Free-IPTV** [comment]
Hi @rduetsch,

die Einladung kommt über Email und zwar über die Mail-Adresse, die du bei Github registriert hast. Ich habe nochmal eine neue Einladung raus geschickt. :-)

**Comment by rduetsch** [comment]
thx erhalten...
