### ISSUE TITLE
Hey Rob. :-)

### ISSUE THREAD

**Issue by Free-IPTV** [Free-IPTV/Countries#281]
Hi @robtayl0r,

i has send a invitation to you. It´s comming per Email, that you has register at Github!

It´s for the new PRIVATE repo, many m3u´s. ;-)

I don't know how else to get in touch with you.

**Comment by cretzujtm** [comment]
helo  its  posibile   send  me    invitation of   new   list  iptv   thank  alot

**Comment by Free-IPTV** [comment]
> 
> 
> helo its posibile send me invitation of new list iptv thanks alot

Can´t you read? Thiss Issue is for **ROB!!!** Instructions to come in the new repo is standing in the Readme! Read the readme. Thank you!
