### ISSUE TITLE
Sent Payment

### ISSUE THREAD

**Issue by danartif** [Free-IPTV/Countries#284]
Hi 

I've sent payment for private repo

**Comment by Free-IPTV** [comment]
Hi @danartif,

in the payment no username, which country?

**Comment by danartif** [comment]
Sorry, was from UK. I just sent 1p with username

**Comment by Free-IPTV** [comment]
First name of sending name? There is no 1P

**Comment by danartif** [comment]
Handy

**Comment by Free-IPTV** [comment]
You can choose and win or lose.... Tablet, Handy or Notebook as first name, sorry my humor! I like Monty Phyton!!!

**Comment by danartif** [comment]
Lol haha! Handy!

**Comment by Free-IPTV** [comment]
Congratulation! You are the winner! Invitation comes via Github email! Welcome!
