### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by snakecr** [Free-IPTV/Countries#285]
Hi really appreciate the proyect (im from Costa Rica), i use the Mexico and Spain list to see some tv, i donated via paypal to support and keep to good work. Greetings from Costa Rica

**Comment by Free-IPTV** [comment]
Hi snaker,

sorry, Why don't you read the readme !!! Unfortunately no users with brand new accounts at the moment. Sorry, I'll send the money back!

**Comment by Free-IPTV** [comment]
Hi @snakecr,

read text above??? Please contact us here! Thank you. :-)
