### ISSUE TITLE
Repo status question

### ISSUE THREAD

**Issue by Xmetalfanx** [Free-IPTV/Countries#290]
Hello ... I have been thinking about this for a day or two and sorry if this is not the place to ask but I am not sure where/how else to ask.

I am NOT asking for access to the private repo, but just as a user (the fact the streams are legal is one of the reasons I use these, and thank all the people that have contributed to the lists) who uses these M3u's in my Kodi install on my android box, I am unsure about what is going on for .. how do i say it ... "normal users" ... as in this repo completely being removed due to those other repos taking the content, and only the private repo will be accessible? (meaning the sources will not work at some point)  

I totally get the anger at the hard work put in and other repos not even giving credit at the very least to the work of this repo and the people who have contributed.   

I know emotions seem to be high and I am just trying to understand what is going on (even after reading the README) as an "average user" who ironically just recently found this repo and as I said one of the reasons I love it is the LEGAL streams and the fact I dont have to worry about random illegal stuff (I dont take chances) in any of the lists.

Again sorry if this isn't the place to ask, but I know i cant be the only one who is unsure after the past few days.

Thanks for your time

**Comment by Free-IPTV** [comment]
Hi @Xmetalfanx 

You know, we make updates every day.

1. Find new streams
2, Find the right logos and integrate them with imgur.com
3. Find the new addresses for dead streams
4. and so on ...

After the updates are out, a short time afterwards the first streams that we created shortly before are circulating with others!

The tag tvg-logo = is a clear indicator of the CLAWING of our work

Example:
tvg-logo="https://i.imgur.com/qlHjCwj.jpg"

This link code "qlHjCwj" is a unique code. A new (different) code is generated for each logo.

In the meantime, for example, IPTV-ORG has HUNDREDS of the link codes for the logos where WE did the work.

Free IPTV means that there are free streams, but it does not mean that everyone can do what they want with it. The rules are clear in the readme!

After our work appeared more and more in forums, websites and etc., we were fed up and therefore there are NO more updates in this repo.

We do the work, other IDIOTS copy it and make a name for themselves in other repos, homepages, forums! That’s over now!

The new private repo finally gives us the opportunity to stop this stealing of our work. I'm sorry, but our patience is at the end, there is no other way.
