### ISSUE TITLE
A request for clarification

### ISSUE THREAD

**Issue by leonardoivo** [Free-IPTV/Countries#291]
A doubt,

**Comment by Free-IPTV** [comment]
Now post here again ??? Sorry, answer there!

https://github.com/Free-IPTV/Countries/issues/257#issuecomment-817094318

**Comment by leonardoivo** [comment]
Dear,
    I asked this, because you said that the donation was not mandatory to have access to the new repository. That's why I asked you. I think that had to be made clear. I asked to enter this new repository and you conditioned the access to the donation and then in another post you say that it is not a precondition to have access to it. So what is it really worth? If it is not mandatory, why don't you grant me access? You understood my questioning. I advise you to make this very clear in the document so that there is no doubt. Thanks in advance.
Graciously,

**Comment by leonardoivo** [comment]
I am not questioning the question of the donation, but the answers, as they seem dubious. One hour you say that to have access you have to donate and in other posts you say that it is not mandatory. I would have no problem doing it. The problem is to know what is really worth, since I want to contribute financially, and with new links and have access to the new repository. But it is important that the rules of this new repository are clear and that they are defined there in that document too and not everything is there.

**Comment by Free-IPTV** [comment]
What is this now, I really have more important things to do than constantly responding to your texts. In addition, it is closed at the moment anyway! I don't feel like doing this whole circus. If work is no longer worth anything to you, there are enough m3u's ... that are not looked after take them!

**Comment by Free-IPTV** [comment]
> A doubt,

Hi @leonardoivo, 

First you annoy here without end, then you continue via email! Who so penetrating over several days by email nervt, comes NOT in the new private repo. Change your behavior!
