### ISSUE TITLE
Watch private repo

### ISSUE THREAD

**Issue by Goldiefresh** [Free-IPTV/Countries#295]
Hi.could you add me to your repo please. Keep up the good work you do. Keeping me sane during this crazy time. Thank you.

**Comment by Zhoro-111** [comment]
Hello and thank you for your interest.You will get a response by tomorrow morning.The repo owner it's not online for today.

**Comment by Free-IPTV** [comment]
Hi @Goldiefresh 

I think, you did not read the readme correctly, ITEM 9

There is no other way at the moment, sorry!
