### ISSUE TITLE
Hypnotix is allowed?

### ISSUE THREAD

**Issue by KernelGM** [Free-IPTV/Countries#296]
Hello, I want to use it on a program called Hypnotix just to watch TV at home.
Does anyone know if it is allowed? And how to configure?

**Comment by Zhoro-111** [comment]
Hello,what do you mean by"allowed"?
I never used Hipnotix but lots of people been using the list on Hipnotix.Configuration same as every M3U player (M3U link on URL field)

**Comment by Free-IPTV** [comment]
Hi @KernelGM,

sorry, here is no Hypnotix Support, use this!

https://github.com/linuxmint/hypnotix/issues
