### ISSUE TITLE
Can I please have access to it?

### ISSUE THREAD

**Issue by krugerl** [Free-IPTV/Countries#303]
Can you please give me the access?
Thank you very much

Thanks also for your effort

**Comment by Free-IPTV** [comment]
Hi @krugerl 

Thank you for your interest in our collection of over 80 m3u's.

Our repo offers one of the best-kept collections of m3u's. It now includes 3997 free and legal streams.

This collection of m3u's requires a lot of work, we do updates almost every day. We ask ourselves more and more, what is such work still worth today?

There are now a lot of offers at the m3u's but what good are they. Often you will find late and dead streams or they are only updated occasionally.

Think about it. You are welcome to make a voluntary donation to show us what a really well-kept collection of m3u's is worth to you.

What would a donation be worth to you for the extensive work of 3 months?

For a voluntary donation please use the link and be sure to include your username from Github: https://paypal.me/FreeIPTVGitgub (YES... Haha, the name FreeIPTVGitgub is correct)

**The donations are to be a recognition of our work. They have NO reference to the free streams or free access to the PRIVATE repo!**

Thank you
