### ISSUE TITLE
fork gelöscht

### ISSUE THREAD

**Issue by rduetsch** [Free-IPTV/Countries#305]
Hallo 
Ich habe die angegebenen schritte durchgeführt, ich dachte, dass ich kolaborieren kann bei den schweizer sender, da ich diese grundsätzliche schaue und auch sehe wenn die streams unterbrechen darum habe ich auch ein fork gemacht, sorry wenn das für dich nicht in ordnung war. gruss r

**Comment by Free-IPTV** [comment]
Ich habe dich zweimal per Email angeschrieben, keine Reaktion!
Ich habe dich im privaten Repo dreinmal per Issue angeschrieben mit @rduetsch , da bekommst du jeweils eine message, keine Reaktion!

Bevor du die Einladung bekommen hast, habe ich es noch einmal EXTRA erwähnt, Thema Forks! 

https://github.com/Free-IPTV/Countries/issues/279#issuecomment-814820310

Kaum warst du im neuen Repo, als erste Aktion, sofort ein Fork erstellt. 

Ich muss das nun erstmal mit meinen Team-Partner besprechen!

**Comment by rduetsch** [comment]
Guten Tag 

Ich habe Dich in diesem falle falsch verstanden, ich bin davon ausgegangen, dass ich ein fork erstellen kann um unterbrochene streams zu aktualisieren. entschuldige die umstände.

Gruss R

PS: wie ich schon versucht habe zu erklären habe ich nur private interessen der benutzung der streams da ich in spanien wohne und über sat nich alles erhalte.

**Comment by Free-IPTV** [comment]
Okay, zweite und letzte Chance, bei nur gelegentlichen Änderungen braucht man kein Fork, da reicht ein Issue. Einladung kommt per Mail!

**Comment by rduetsch** [comment]
danke
