### ISSUE TITLE
Private Repo Access

### ISSUE THREAD

**Issue by macumbero71** [Free-IPTV/Countries#307]
Hi.  Is possible to have accesso to the Private Repo  ? Thanks for your work

**Comment by marreromarco** [comment]
Hi. I also agree with the new Terms & Conditions.  Could I please access the new repo ?

Thanks for your great work !

**Comment by Free-IPTV** [comment]
I think, you did not read the readme correctly, ITEM 9

There is no other way at the moment, sorry!
