### ISSUE TITLE
New, Legal Streans

### ISSUE THREAD

**Issue by christiankaye** [Free-IPTV/Countries#312]
I have been managing this list for several months, maybe for more than two years. Should be 100% working and legal. All USA Channels. Please consider removing Miami TV from your USA Channel list. It contains adult content.

Here is the list:
https://github.com/christiankaye/radio_television

**Comment by Free-IPTV** [comment]
Thank you for your important info, the stream will be deleted. With 3997 streams, one can sometimes be overlooked that does not belong in there.
