### ISSUE TITLE
Rogério Torrres

### ISSUE THREAD

**Issue by rogerioronin** [Free-IPTV/Countries#313]
Hello I would like to participate, I only use the m3u on my equipment and my family's!

Sorry for the bad english!

**Comment by Free-IPTV** [comment]
Hi @rogerioronin,

my english is also not so good! ;-)

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you
