### ISSUE TITLE
Private access

### ISSUE THREAD

**Issue by TheBrit007** [Free-IPTV/Countries#315]
Hello, my access to private has been taken away but not sure why, I have not violated any terms

**Comment by Free-IPTV** [comment]
Hi @TheBrit007,

you created a fork of the private repo without discussing it with me beforehand! You don't need a fork to use the m3u's for private use. This "stupid forking" is not tolerated in our private repo. What do you have to say about it?

**Comment by TheBrit007** [comment]
I didn't create the fork. It must have Ben clicked on by my kid while the
computer open or something.  I have no reason for forks, I'm just using it
for my living room and my kids. I apologize that got created

**Comment by Free-IPTV** [comment]
You kids create a fork??? Sorry...  i will sleep over there for a night and discuss it with my team partner from the repo! I'll let you know tomorrow!

**Comment by TheBrit007** [comment]
No, I mean I think they may have clicked on the mouse and were clicking on
buttons.  I had left the computer on and was not locked.  Again I have no
need for a fork as it is just me with personal in home use.  My child likes
to copy what I do on the computer,  he is young.  I apologize for the issue
but was not done to violate terms or myself did the creation

**Comment by Free-IPTV** [comment]
Second and last chance, invitation is out!

**Comment by TheBrit007** [comment]
Thank you, I appreciate it.  I'll be double checking from now.
