### ISSUE TITLE
New repo access 

### ISSUE THREAD

**Issue by ismailcherri** [Free-IPTV/Countries#317]
Hi, I agree to the rules and would like to have access to the private repo.

Thanks in advance!

**Comment by i82blikeu** [comment]
Hello,  agree to the rules and would like to have access to the private repo.

Ciao e grazie.

**Comment by Free-IPTV** [comment]
Hi @ismailcherri 

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you
