### ISSUE TITLE
Wrong channels in INDIA list.

### ISSUE THREAD

**Issue by bishal5588** [Free-IPTV/Countries#32]
92 news and zindagi tv is not indian channels.

**Comment by Free-IPTV** [comment]
Hi bishal5588,

okay, thank your for this information. I remove these Streams and at the next uploads it is correct.

Greetings from Germany :-)

**Comment by Free-IPTV** [comment]
I have looked, zindagi tv is an indian channel!

Look there:

https://en.wikipedia.org/wiki/Zindagi_(TV_channel)

92 news  is Pakistan. ;-)

**Comment by bishal5588** [comment]
you can see it is discontinued in 1 july 2017. and the link of the zindagi tv is from pakistan. pleasr remove it and remove 92 news
