### ISSUE TITLE
Access to new private repo

### ISSUE THREAD

**Issue by nomadtab** [Free-IPTV/Countries#323]
Hello, I read and agree with the rules and would like to have access to your private repo.
Best,

**Comment by Free-IPTV** [comment]
Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you

**Comment by nomadtab** [comment]
Hello, I read and agree with the rules and would like to have access to your private repo.
Could you please post again the email?
