### ISSUE TITLE
to access your repo

### ISSUE THREAD

**Issue by sdiagne** [Free-IPTV/Countries#328]
Hi,
I want to access repo. Can you give me the access please?

**Comment by moedele** [comment]
Can you add me too?, thanks a lot

**Comment by sdiagne** [comment]
Hi,
Can you add me too?
thanks a lot

**Comment by Free-IPTV** [comment]
> 
> 
> Can you add me too?, thanks a lot

Hi @moedele,

I think, you did not read the readme correctly, ITEM 9

There is no other way at the moment, sorry!

**Comment by Free-IPTV** [comment]
Hi @sdiagne,

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you
