### ISSUE TITLE
US CBS and CNBC not working

### ISSUE THREAD

**Issue by CryoRenegade** [Free-IPTV/Countries#33]
US CBS and CNBC not working
VLC is unable to open the MRL 'https://edge-1192-ch-gv.filmon.com/live/4130.high.stream/playlist.m3u8?checkedby:iptvcat.com'. Check the log for details.
gh.stream/playlist.m3u8?checkedby:iptvcat.com'. Check the log for details.

**Comment by Free-IPTV** [comment]
Hi CryoRenegade,

in the my list US01_USA there is no CBS, there is only CBSN and this works. I has this tested with VLC (Windows) now:

 #EXTINF:-1 tvg-name="CBSN" tvg-id="CBS Eastern US" group-title="USA" tvg-logo="https://i.imgur.com/nki2HDQ.png",CBSN
http://cbsnewshd-lh.akamaihd.net/i/CBSNHD_7@199302/master.m3u8

did you use an old fork? Here at Github are so much old forks, i hate this. ;-)

The link for CNBC is broken, i update this and make a update.. Thank you for your old information. :-)

Whem the link for CBSN works again, i close this Issue. 

Greetings from Germany

**Comment by CryoRenegade** [comment]
Thank you for the response!

**Comment by Free-IPTV** [comment]
I has make the Update! Thank you also. :-)
