### ISSUE TITLE
Access to Private Repo

### ISSUE THREAD

**Issue by yoharnu** [Free-IPTV/Countries#331]
I would like access to the private repo, and I agree to the terms you listed. And thank you for your work

**Comment by JoPeSch** [comment]
Dear all, as a newbie I‘d also like to get access to a private Repo, of course I do accept the rules (terms and conditions) and I will use the .m3u’s only privately. Please provide me with a step by step how to guide. Many thanks in advance. Best regards JoPeSch

**Comment by Free-IPTV** [comment]
Hi @JoPeSch ,

I think, you did not read the readme correctly, ITEM 9!!! GRRRR...

There is no other way at the moment, sorry!

**Comment by Free-IPTV** [comment]
Hi @yoharnu 

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you
