### ISSUE TITLE
Access to repo

### ISSUE THREAD

**Issue by mr-gmz** [Free-IPTV/Countries#333]
Hi guys, can I get access to the new repo?

**Comment by Jmunsey859** [comment]
like mr-gmz i was looking for access,  I recently switched back to blackarch from garuda, and miss the hypnotix looking to konnect. my account is super old but if you need anything HMU.. Danka

**Comment by Free-IPTV** [comment]
Hi  Jmunsey859  and mr-gmz,

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 3997 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Thank you

**Comment by Jmunsey859** [comment]
Hola gmx, im following up with the email from the github post, im still interested in the repo. thanks and iI appriciate your work even if no one else says it...

**Comment by Free-IPTV** [comment]
https://github.com/Free-IPTV/Countries/issues/333#issuecomment-819721007
