### ISSUE TITLE
Looking to get access to new repo

### ISSUE THREAD

**Issue by Hypercypher10** [Free-IPTV/Countries#342]
Hi there,

I've been looking to find a free IPTV channel for my elderly father. He's a fan of cp24 (news channel) from Canada but I have not been able to find any working m3u files for this. 

I came across your post that you had on Twitter and was curious to know what you had to offer. I'm new to this, so not sure if I'm in the right place. If I could get access to check things out, that would be fantastic.

Thank you in advance

**Comment by Free-IPTV** [comment]
I think, you did not read the readme correctly, ITEM 9

There is no other way at the moment, sorry!
