### ISSUE TITLE
Requesting access

### ISSUE THREAD

**Issue by MapGuy11** [Free-IPTV/Countries#346]
Hello,

I have loved and contributed access to this Repo and am sad that it had to go because of some bad "eggs".

If I could request access that would be awesome!

**Comment by Free-IPTV** [comment]
Hi,

you don´t need access to our m3us, you offer some yourself!

https://github.com/MapGuy11/the6tv

**Comment by MapGuy11** [comment]
I am surprised you closed it already this was a old list of some locals that I found links for.

**Comment by MapGuy11** [comment]
> Hi,
> 
> you don´t need access to our m3us, you offer some yourself!
> 
> https://github.com/MapGuy11/the6tv
I am surprised you closed it already this was an old list of some locals that I found links for.

**Comment by Free-IPTV** [comment]
Just stay there, you have forked the dubious stuff:

 iptv-org/iptv

Bye!
