### ISSUE TITLE
Requesting access

### ISSUE THREAD

**Issue by zsabit** [Free-IPTV/Countries#347]
Hi, 

I was looking for free IPTV and found this on google. It would be very nice if I could get access to your repo.

**Comment by craftsman777** [comment]
I believe in giving credit where credit is due and therefore understand the pain of your work being stolen and taken credit for.
Please give me access to the private repo.
Thanks

**Comment by bernie1968** [comment]
Hi, I'm requesting free access. Many many greetings from The Netherlands!

**Comment by Free-IPTV** [comment]
Please read the readme EXACTLY! Thank you!
