### ISSUE TITLE
Add this Channels

### ISSUE THREAD

**Issue by bishal5588** [Free-IPTV/Countries#35]
otv
https://cdn.smartstream.video/smartstream-us/otvnewmbr/otvnewmbr.smil/playlist.m3u8
Kalinga TV
https://live.mycast.in/kalingatv/d0dbe915091d400bd8ee7f27f0791303.sdp/playlist.m3u8
Zee Odisha
https://z5ams.akamaized.net/kalinga/index.m3u8?hdnts=st=1607508707~exp=1607511707~acl=/*~hmac=bb3b19ce3357d05e7f790447e6bb5b5d3d52f8928ad16fc787968837d14f2d96
Pramaya News7
https://live.mycast.in/encode/ee0c5a36ff5a7083ee044991974ad3ba.sdp/playlist.m3u8
Kanak News
https://live.kanaknews.com:4443/live/stream/playlist.m3u8
Nandighosha Tv
https://live.mycast.in/ngtv/d0dbe915091d400bd8ee7f27f0791303.sdp/playlist.m3u8
News18 Odia
https://etv-oriya.akamaized.net/i/n18odia_1@179753/master.m3u8?hdnea=st=1607509617~exp=1607545617~acl=/*~hmac=16435640594e2c073a2a1b7876416da0631cde61e6a09040879d84dfd1c51fd1
Naxtra News
http://wearelive.livebox.co.in/naxatratvhls/Naxatratv.m3u8
Aaj Tak
https://aajtaklive-amd.akamaized.net/hls/live/2014416/aajtak/aajtaklive/playlist.m3u8
News18 Hindi
https://news18india-lh.akamaihd.net/i/news18india_1@174951/index_4_av-b.m3u8
News24
https://vidcdn.vidgyor.com/news24-origin/liveabr/news24-origin/live1/chunks.m3u8
NDTV
https://ndtvindiaelemarchana.akamaized.net/hls/live/2003679/ndtvindia/ndtvindiamaster.m3u8
Prive Tv HD
https://y5w8j4a9.ssl.hwcdn.net/andprivehd/tracks-v1a1/index.m3u8
AajTak HD
https://feeds.intoday.in/aajtak/api/aajtakhd/master.m3u8
CNBC TV18
https://cnbctv18-lh.akamaihd.net/i/cnbctv18_1@174868/index_5_av-p.m3u8
CNBC AWAAZ
https://cnbcawaaz-lh.akamaihd.net/i/cnbcawaaz_1@174872/index_5_av-p.m3u8
India News
https://m-c036-j2apps.s.llnwi.net/hls/0442.IndiaNews.in.m3u8
Republic Bharat
https://republic.pc.cdn.bitgravity.com/live/bharat_hls/master.m3u8
Republic TV
https://weblive.republicworld.com/liveorigin/republictv/master_hdlive_360p.m3u8
Shemaroo Kids
https://livechannel.shemaroome.com/linearplayout/kids-linear-channel/chunklist_640x360_cf.m3u8
WION TV
http://z5amshls.akamaized.net/wion/tracks-v1a1/playlist.m3u8
Times Now
http://timesnow-lh.akamaihd.net/i/TNHD_1@129288/index_720_av-p.m3u8
Times Now HD
https://timesnow-lh.akamaihd.net/i/TNHD_1@129288/master.m3u8
Zee Bollwood
http://z5amshls.akamaized.net/classic/tracks-v2a1/playlist.m3u8
Zee News
https://zmcl-live.akamaized.net/zeenewsclean_mbr/index.m3u8?hdnts=st=1607509766~exp=1607512766~acl=/*~hmac=b0891fd69bc6a0783203529934bc82a562c9b7a6d9215f3759bac7a30068e556
DW NEWS
http://dwstream4-lh.akamaihd.net/i/dwstream4_live@131329/index_1_av-p.m3u8
DW NEWS HD
https://m-c010-j2apps.s.llnwi.net/hls_hd/8024.DWEnglishHD.in.m3u8
ET NOW
http://etnowweblive-lh.akamaihd.net/i/ETN_1@348070/index_576_av-b.m3u8
Gabruu TV
http://104.237.60.234/live/gabruutv.m3u8
MNX
https://timesnow.airtel.tv/live/MNX_pull/master.m3u8 
CNN NEWS
https://vootlive-i.akamaihd.net/hls/live/799896/cnnnews18voot/master_5.m3u8
Romedy Now
https://timesnow.airtel.tv/live/RN_pull/master.m3u8
TANGY PUNJABI TV
http://cdn9.live247stream.com/punjabitvcanada/tv/punjabitvcanada/livestream/chunks.m3u8
Eetlive
https://live.streamjo.com/eetlive/eettv.m3u8

**Comment by Free-IPTV** [comment]
Hi bishal5588,

this are not all India TV, for example DW News or CNN News. What are India TV???

Greetings from Germany

**Comment by Free-IPTV** [comment]
I have added the channels.

These streams wars also in my list:
CNBC AWAAZ, CNBC TV18, ET NOW, NDTV, Republic Bharat, Republic TV, Times Now

Don't use these old forks, some of which are available here from my repo. Always look in my repo, that's up to date.

 Zee Odisha has an expiration date in the stream, works only for a short time.

Thanks for your help!

Greetings from German
