### ISSUE TITLE
Zugriff auf die Listen

### ISSUE THREAD

**Issue by CustomerJFK** [Free-IPTV/Countries#351]
Hallo

Wie ist der Weg um auch zukünftig Zugriff auf die IPTV Listen zu bekommen.
Ich schätze ihre Arbeit wirklich sehr und würde mich freuen eine Rückinof zu erhalten.

Beste Grüße und bis bald!

**Comment by Free-IPTV** [comment]
Hi @CustomerJFK,

endlich mal jemand, den ich vom alten Repo her kennen.

Schreib mich bitte per Mail an, gib deinen Github Usernamen mit an: freeiptv-github@gmx.de

Ich danke dir. Danach lösche ich das Issue!
