### ISSUE TITLE
I agree to your conditions 

### ISSUE THREAD

**Issue by Paderman** [Free-IPTV/Countries#355]
Hello :smiley: 
I agree with your conditions and I will be happy :+1: :angel:
 
Thank you in advance :handshake: :smiley:

**Comment by Free-IPTV** [comment]
Hi @Paderman,

Thank you for your interest in our collection of over 80 m3u' and at the moment exact 4103 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

After that, I'll delete this. Thank you

**Comment by Free-IPTV** [comment]
Hi @Paderman,

you should already write to me by email, otherwise we won't get further and I'll delete this ;-)
