### ISSUE TITLE
Private Access

### ISSUE THREAD

**Issue by rdroberton** [Free-IPTV/Countries#360]
I agree to all terms and conditions.

**Comment by Free-IPTV** [comment]
> 
> 
> I agree to all terms and conditions.

Hi @rdroberton,


Thank you for your interest in our collection of over 80 m3u' and at the moment exact 4103 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

After that, I'll delete this. Thank you

**Comment by Free-IPTV** [comment]
Hi @rdroberton,

you should already write to me by email, otherwise we won't get further and I'll delete this ;-)
