### ISSUE TITLE
Terms Agreed to, Access to Private Repo please?

### ISSUE THREAD

**Issue by lrm864** [Free-IPTV/Countries#362]
I have been around Github for a while, since late 2019. I wanted Github to hold some EPG files privately, but it wasn't really working for me since I would need to pay to get rid of the token the URLs would give me. I do have one private repo, but I haven't done anything to it in a while. I would like access to the private repo if it is possible? I understand that your rules are strict, but I agree to your rules, and I will stick by it. Please let me know if it is possible, or if you have any comments or concerns.

**Comment by Free-IPTV** [comment]
Hi @lrm864,

In our private repo we also work with tokens in the links for the m3u, Then this will probably not be the right thing for you.

**Comment by lrm864** [comment]
Dear @Free-IPTV ,
I understand that your m3u links will have tokens in them. If you are paying access to Github, you wouldn't have tokens, but since me and you are free users, there will be tokens in the m3u files that are hosted privately. Unless you are talking about the actual streams that have tokens in them, then I understand as well as those are official streams. Do you think we could talk via e-mail if that is possible? I understand the time difference, and you may not see this, but I understand what you are saying. All I want, if possible, is access to your private repo to see what you have.
Sincerely,
lrm864

**Comment by Free-IPTV** [comment]
I am a Pro member and pay for Github. Nevertheless, the links have tokens and THAT is good, because in the end I can use them to make some rules ;-)

I am a Pro member and pay for Github. Nevertheless, the links have tokens and THAT is good, because in the end I can use them to make some rules ;-)

Just to see what I have, there is certainly no access for that, sorry!
