### ISSUE TITLE
i agree to the terms

### ISSUE THREAD

**Issue by cuipito** [Free-IPTV/Countries#367]
I agree to the therms that you provided, and would like access to the repo thank you in advance.

**Comment by Free-IPTV** [comment]
Hi @cuipito,

thank you for your interest in our collection of over 80 m3u' and at the moment exact 4127 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.
