### ISSUE TITLE
Access to private repo | I agree to the terms

### ISSUE THREAD

**Issue by rnbunker** [Free-IPTV/Countries#368]
As the title says, I would like to get access to the private repo so I can watch some TV in hypnotix!

**Comment by Free-IPTV** [comment]
Hi @rnbunker,

thank you for your interest in our collection of over 80 m3u' and at the moment exact 4127 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.
