### ISSUE TITLE
Non-Indian channels

### ISSUE THREAD

**Issue by bishal5588** [Free-IPTV/Countries#37]
Pakistani Channels
1-92 news
2-Hum tv HD
3- hum News
4-Lahore News
5-Subrang TV(USA)
6-Tag TV
7-Zindagi TV

Srilanka Channels
1-ITN TV
2-Nethra TV

**Comment by Free-IPTV** [comment]
Hi bishal5588,

okay, i remove this streams, in the next update <ou can see it. 

Greetings from Germany
