### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by brickleroux** [Free-IPTV/Countries#374]
I've read the conditions for the use of the private repo and i fully agree to it. Please can I get access?
Thanks.

**Comment by Free-IPTV** [comment]
> 
> 
> I've read the conditions for the use of the private repo and i fully agree to it. Please can I get access?
> Thanks.

Hi @brickleroux,

it's not that simple anymore. You can contact me for more info by mail: freeiptv-github@gmx.de

Afterwards I remove the mail-address here again, otherwise countless people contact me again without ISSUE and that is annoying ;-)

**Comment by Free-IPTV** [comment]
No answer is also an answer. Email address removed, issue closed ;-)
