### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by Jakgab617** [Free-IPTV/Countries#375]
Hi, can you please give me access to your repo?

Thanks

**Comment by Free-IPTV** [comment]
> 
> 
> Hi, can you please give me access to your repo?
> 
> Thanks

Hi @Jakgab617,

For further information please contact me per email: freeiptv-github@gmx.de

**Please include your Github username in the email.** 

Afterwards I remove the mail-address here again, otherwise countless people contact me again without ISSUE and that is annoying ;-)
