### ISSUE TITLE
Indian channel exp

### ISSUE THREAD

**Issue by bishal5588** [Free-IPTV/Countries#38]
There is 2 channels have exp zee news and news 18 odia

**Comment by Free-IPTV** [comment]
Hi bishal5588, 

the 2 streams use an expiration date! You have given me the 2 addresses but I will remove them again. Some streams cannot be received over a longer period of time via an M3U, that's just how it is. Thanks for your information. :-)

**Comment by Free-IPTV** [comment]
Hi bishal5588,

i have test the 2 channels, Only news 18 odia does not work. zee news works in my m3u here. Don´t use old fucking shit forks. Here are very much shit old Forks. I DO NOT GIVE SUPPORT FOR OLD AND UNKEMPT FORKS!

Gretings from Germany

**Comment by bishal5588** [comment]
OK
