### ISSUE TITLE
Access to private repo request

### ISSUE THREAD

**Issue by WolfganP** [Free-IPTV/Countries#389]
Hi, long time user of your lists, missing the curation work you put in day after day.
I'll be able to collaborate on Argentina's lists.
Thanks in advance!

**Comment by Free-IPTV** [comment]
Hi,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.
