### ISSUE TITLE
- Blocked because of your stupid mails! -

### ISSUE THREAD

**Issue by freeseacher** [Free-IPTV/Countries#390]
I'm agree to rules

**Comment by Free-IPTV** [comment]
Hi,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.

**Comment by Free-IPTV** [comment]
Hi @freeseacher,

Now that you're making us look stupid via email, making claims that aren't true, your account is blocked from our profile here! Learn to behave yourself first and stop making us look stupid via email!
