### ISSUE TITLE
access request

### ISSUE THREAD

**Issue by dreamonates** [Free-IPTV/Countries#391]
hi,
i would like to request access to your new tv lists. i'll be using them on my tv.
i've read your rules.
i can help with adding Turkish streams if you want. 

thanks in advance.

**Comment by Free-IPTV** [comment]
Hi,

Thank you for your interest in our collection of over 80 m3u' and at the moment more than 4600 free and legal streams.

For further information please contact me per email: freeiptv-github@gmx.de

Please include your Github username in the email. After that, I'll delete this issue here.
