### ISSUE TITLE
Access to private repo

### ISSUE THREAD

**Issue by Fernsehhunter** [Free-IPTV/Countries#393]
Hello, I read all the rules and agree to them. I can understand the caution. Thank you for your whole work and I like to watch TV for private use only. :)

**Comment by Free-IPTV** [comment]
Hi Fernsehhunter,

danke für deine Anfrage, kannst ja deutsch, weiss ich. Bist ja auch im Kodinerds Forum.

Hier erst mal deine Frage, Welt.de Stream, mache ich normalerweise nicht, Support an Nicht-Mitglieder des geschlossenen Repos:

#EXTINF:-1 tvg-name="WELT" tvg-id="WELT.de" tvg-logo="https://logos.zattic.com/images/channels/logos/2e460a3011ecd55bd3b9/black/84x48.png" group-title="GERMANY",WELT
https://live2weltcms-lh.akamaihd.net/i/Live2WeltCMS_1@444563/master.m3u8

Wichtig ist immer, das habe  auch bei Kodinerds viele nicht kapiert... immer die master, playlist oder index nehmen, wegen Ausfallsicherheit. So einige Idioten haben mich bei Kodinerds ja rausgeeckelt... seit dann ist das Thema IPTV da eh fast tot, nix mehr los. ;-)

Kontakte mich per Mail, dann schnacken wir über den Zugriff auf das geschlossene Repo mit über 4660 legalen und freien Streams: freeiptv-github@gmx.de

**Comment by Free-IPTV** [comment]
Hi @Fernsehhunter,

hole bitte die Mail von Github-Email ab, ist wichtig! ;-)
