### ISSUE TITLE
priv repo

### ISSUE THREAD

**Issue by putzipuh** [Free-IPTV/Countries#396]
Hey, I agree to your conditions. Thanks :)

**Comment by Free-IPTV** [comment]
Hi putzipuh,

danke für deine Anfrage, kannst ja deutsch, weiss ich. Bist ja auch im Kodinerds Forum.

Kontakte mich per Mail, dann schnacken wir über den Zugriff auf das geschlossene Repo mit über 4660 legalen und freien Streams:  freeiptv-github@gmx.de

Wenn ich deine Mail habe, lösche ich die Adresse hier dann wieder. Es kommen sonst wieder ständig mails von usern ohne Issue. ;-)

**Comment by Free-IPTV** [comment]
> Wenn ich deine Mail habe, lösche ich die Adresse hier dann wieder. Es kommen sonst wieder ständig mails von usern ohne Issue. ;-)

Sorry, du bist ja auch einer von denen, die bei Kodinerds ständig auf dem Thema rumgeritten haben, wegen angeblich illegalen Stream in einer meiner m3u´s! DU bekommst keinen Zugriff und Tschüss!!!

https://www.kodinerds.net/index.php/Thread/71520-Weitere-freie-und-legale-Streams-f%C3%BCr-Kodi/?postID=631914#post631914
