### ISSUE TITLE
access to private repo

### ISSUE THREAD

**Issue by patrickdrd** [Free-IPTV/Countries#397]
Hello, 
I have read the rules and agree. 
Thank you for your hard work.

I would like access to private repo for private use only.

thanks

**Comment by Free-IPTV** [comment]
> 
> 
> Hello,
> I have read the rules and agree.
> Thank you for your hard work.
> 
> I would like access to private repo for private use only.
> 
> thanks

Sorry, you don't need our repo, just continue to stay with IPTV-Org. 

Your ISSUE there 2876! I don't put a link to the dubious repo with partly illegal streams ;-)
