### ISSUE TITLE
M3u

### ISSUE THREAD

**Issue by forodian** [Free-IPTV/Countries#4]

**Comment by Free-IPTV** [comment]
M3u???

**Comment by forodian** [comment]
Hello yes thanks

**Comment by DUVVI** [comment]
indian m3u8 file

**Comment by Free-IPTV** [comment]
I have no Indian .m3u

**Comment by Free-IPTV** [comment]
> 
> 
> _No description provided._

I has no epg but you can use this to become EPG in your .m3u: https://raw.githubusercontent.com/oe-alliance/oe-alliance-core/4.0/meta-oe/recipes-oe-alliance/enigma2-plugins/epgimport-rytec/rytec.sources.xml
