### ISSUE TITLE
Private Repo

### ISSUE THREAD

**Issue by bruinfan000** [Free-IPTV/Countries#408]
hi is it possible to get a private repo. Thanks

**Comment by bruinfan000** [comment]
this is my first time here so im not sure what the procedure is.Thanks

**Comment by bruinfan000** [comment]
i am not looking for a free b, at the expense of your hard work  I'm willing to do my part and donate to help keep your work going.Thanks

**Comment by Free-IPTV** [comment]
What you make is like SPAM! Don't you think an ISSUE with a request is enough?
