### ISSUE TITLE
Nickelodeon HD

### ISSUE THREAD

**Issue by CustomerJFK** [Free-IPTV/Countries#41]
Could you add Nickelodeon HD to the list please?
Thanks!!!

**Comment by Free-IPTV** [comment]
Which country??? In Germany isn´t free tv!

**Comment by Free-IPTV** [comment]
and... if you want Nick in Germany, have a look in my DE04_GERMANY_Pluto.m3u, this is legal and free! :-)

**Comment by Free-IPTV** [comment]
With !In Germany isn´t free tv!" i mean, there is no streams with IPTV... some Private TV in Germany, has NICK but this is not free for all...

**Comment by CustomerJFK** [comment]
OK -Understood
Could you add Bibel TV please?
always German
Thanks
