### ISSUE TITLE
Can i join ?

### ISSUE THREAD

**Issue by Apple-Sam** [Free-IPTV/Countries#412]
Hi, can I join your private repo

**Comment by Free-IPTV** [comment]
Please read the readme! No new accounts. Do you have a reference, a homepage with an email address?

**Comment by Apple-Sam** [comment]
Sorry I dont know what that is

**Comment by Free-IPTV** [comment]
> 
> 
> Sorry I dont know what that is

https://github.com/Free-IPTV/Countries#readme !!!

**Comment by Apple-Sam** [comment]
Is there any other way I can join . I just want to watch live tv. I am not going to share it with anyone

**Comment by Free-IPTV** [comment]
Do you have a reference, a homepage with an email address?

**Comment by Free-IPTV** [comment]
Okay, no answer. As a matter of principle, we deliberately do not allow any new accounts into the closed repo. We have our reasons. I have tried to give the one possibility anyway. If nothing comes, I can't help you either.
