### ISSUE TITLE
channel doesnt work

### ISSUE THREAD

**Issue by poltom30** [Free-IPTV/Countries#419]
hi,

would you pls fix that channel for me?

XTV Music HD (CI)

Thank you!

Tom

**Comment by Free-IPTV** [comment]
> 
> 
> hi,
> 
> would you pls fix that channel for me?
> 
> XTV Music HD (CI)
> 
> Thank you!
> 
> Tom

Hi Tom,

thans for your issue. Updates we make We always do updates in the morning. Tomorrow morning the new address will be in:

https://tls.cdnz.cl/xtvmusic-media/xtvmusic-media/playlist.m3u8

Have a good sunday. :-)

**Comment by poltom30** [comment]
Hi, 
CL: XTV Music HD is down again.
Could you pls fix it?
Thanks you!

Sent from Yahoo Mail on Android 
 
  On H, júl. 19, 2021 at 8:36, ***@***.***> wrote:   


Closed #419.

**Comment by Free-IPTV** [comment]
> 
> Hi,  CL: XTV Music HD is down again. Could you pls fix it? Thanks you! Sent from Yahoo Mail on Android On H, júl. 19, 2021 at 8:36, ***@***.***> wrote: Closed #419. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry but we really don't feel like it anymore. We do the work and some idiots in the IPTV scene constantly copy our work without giving us as a source. This is no fun anymore.
