### ISSUE TITLE
Bibel TV

### ISSUE THREAD

**Issue by CustomerJFK** [Free-IPTV/Countries#42]
Could you add Bibel TV please?
always German
Thanks

**Comment by Free-IPTV** [comment]
Bibel TV... hmm... okay, bist du Deutscher? Warum den Kanal? Kann ihn aber gerne rausuchen und in meine M3U DE03_GERMANY_Local reinsetzen. :-)

**Comment by Free-IPTV** [comment]
Ich warte auf deine Antwort, Kommunikation ist wichtig!

**Comment by Free-IPTV** [comment]
CustomerJFK, answer?

**Comment by CustomerJFK** [comment]
Hallo 
Ja ich bin Deustscher und der Kanal gehört bei mir dazu.
Wäre schön wenn es geht!
Thanks!

**Comment by Free-IPTV** [comment]
Okay, suche ich raus, kommt in die DE03_GERMANY_Local
