### ISSUE TITLE
JSON File

### ISSUE THREAD

**Issue by sourabhsdx** [Free-IPTV/Countries#420]
Can you please upload one JSON file with channel data

**Comment by Free-IPTV** [comment]
> 
> 
> Can you please upload one JSON file with channel data

Sorry, we have no JSON file, please read the redame exactly. This is a repo with m3u´s. ;-)

**Comment by Free-IPTV** [comment]
Hi @sourabhsdx,

you has create a fork, there is comming no pull-request. Didn't you read our readme (part creating fork)???

https://github.com/Free-IPTV/Countries/blob/master/README.md

Greetings

Free-IPTV

**Comment by Free-IPTV** [comment]
@sourabhsdx ???

no answere is also an answer. We don´t accept stupid forking, you´re blocked!
