### ISSUE TITLE
a small correction for UK PLUTO EPG

### ISSUE THREAD

**Issue by dreamonates** [Free-IPTV/Countries#421]
EPG source link for **UK02_UNITED_KINGDOM_Pluto** has been changed. it no longer ends with "uk.xml".

the new working ones are:
https://i.mjh.nz/PlutoTV/gb.xml
https://i.mjh.nz/PlutoTV/gb.xml.gz

thanks for providing iptv lists.

**Comment by Free-IPTV** [comment]
> 
> 
> EPG source link for **UK02_UNITED_KINGDOM_Pluto** has been changed. it no longer ends with "uk.xml".
> 
> the new working ones are:
> https://i.mjh.nz/PlutoTV/gb.xml
> https://i.mjh.nz/PlutoTV/gb.xml.gz
> 
> thanks for providing iptv lists.

Good morning @dreamonates,

thank you for this information. It will be changed in the next update.

:-)
