### ISSUE TITLE
channel skips, freezes, buffers

### ISSUE THREAD

**Issue by poltom30** [Free-IPTV/Countries#422]
hi guys,

pls fix that channel for me, its the best music channel I've ever seen and its not working properly:

Country: NewZealand
Channel: Breeze TV

Thank you!

Best,
Tom

**Comment by Free-IPTV** [comment]
Hi @poltom30,

as you can see, the m3u is coming:
https://i.mjh.nz/nz/tv.68.m3u8

mjh.nz is Matt Huisman so you write your issue please here at: https://github.com/matthuisman

... somewhere where you can write an issue, e.g. at your addons (slyguy.addons).

Greetings :-)

**Comment by poltom30** [comment]
hi,

More than 1000 channels disappeared this morning from your playlist, including Nashville Country TV, The Country Network, The Heartland Network.

Please bring them back!

Thanks!

Best,
Tom

**Comment by Free-IPTV** [comment]
Hi Tom,

No sooner had we got all the streams available again than the lazy sods at IPTV-ORG start doing our work again without giving the source (Free-IPTV).

Thank the idiots, we no longer do the work for others who then want to make a name for themselves under their names, sorry. Why not thank @Sphinxroot directly yourself?

Read this:
https://github.com/Free-IPTV/Countries/commit/55c03fb35356d010cc5d76978714fb7f5630a4f0#commitcomment-53941754

and this:

https://github.com/iptv-org/iptv/issues/3679

Sorry...
