### ISSUE TITLE
Add more channels for Bulgaria

### ISSUE THREAD

**Issue by mynewnickname** [Free-IPTV/Countries#425]
I suggest that you should add common chanels in Bulgarian tv like BTV , BTV HD , NOVA , NOVA HD , BTV Cinema , BTV Comedy

**Comment by Free-IPTV** [comment]
> 
> 
> I suggest that you should add common chanels in Bulgarian tv like BTV , BTV HD , NOVA , NOVA HD , BTV Cinema , BTV Comedy

Hi @mynewnickname,

okay. We can see which streams are available free and legal. We are not IPTV-ORG... Haha. 

Thank you for your issue. :-)

**Comment by Free-IPTV** [comment]
Hi @mynewnickname,

Nova HD:
https://nova.bg/live

The free stream (besite) has a token ?at= so you can´s use this stream with a m3u.

https://e203-ts.cdn.bg/ntv-inter/fls/ntv_1.stream/chunklist.m3u8?at=85944ad13fcffe35ede608b68969a7

also NOVA NEWS:
https://e203-ts.cdn.bg/ntv/fls/NNHD.stream/chunklist.m3u8?at=85944ad13fcffe35ede608b68969a7db

BTV. Is not free, you can´t outside Bulgaria. Also the provider https://voyo.bg/ has BTV streams but this is PAID-TV

https://voyo.bg/priceplans

Issue closed
