### ISSUE TITLE
Italian m3u list some streams stopped

### ISSUE THREAD

**Issue by mcalistri** [Free-IPTV/Countries#427]
Hi dears,

Whenever would be feasible, please be so kind to check the following streams:

IRIS, CANALE 5, CINE 34, FOCUS, RAI NEWS 24, ITALIA 1. I suppose that there are some others streams not working anymore but these above are among the ones I use to watch more frequently.

Thanks for your kind attention.

Best regards.

**Comment by Free-IPTV** [comment]
Hi @mcalistri,

I have sent you an email... Yahoo Mail. Publicly there will be no more news here. There are too many idiots in the IPTV scene.

https://github.com/Free-IPTV/Countries/commit/55c03fb35356d010cc5d76978714fb7f5630a4f0#commitcomment-53941754

https://github.com/iptv-org/iptv/issues/3679 

Best regards

**Comment by Free-IPTV** [comment]
Hi @mcalistri,

i have sent you an email with the m3u to the address i know from you, unfortunately an error comes up, your yahoo email:

multiple delivery attempts failed...

sorry but there is nothing I can do.

**Comment by mcalistri** [comment]
I replied to you regarding the Yahoo error. In this case of obsoleted m3u link, how I should configure my Simple PVR Client on Kodi?

Please tell me by direct message by my e-mail address.

Thanks!

**Comment by Free-IPTV** [comment]
> 
> 
> I replied to you regarding the Yahoo error. In this case of obsoleted m3u link, how I should configure my Simple PVR Client on Kodi?
> 
> Please tell me by direct message by my e-mail address.
> 
> Thanks!

Email is sent ;-)

**Comment by fparri** [comment]
Hello, can I get the M3U, too? :)

**Comment by Free-IPTV** [comment]
> 
> 
> Hello, can I get the M3U, too? :)

Hi fparri,

mail is going to your Email Yahoo. ;-)

**Comment by giovannivetere** [comment]
Please may I have a copy? :)
