### ISSUE TITLE
new channel needed - NDR Mecklenburg-Vorpommern HD -

### ISSUE THREAD

**Issue by CustomerJFK** [Free-IPTV/Countries#428]
Hi
Could anyone help my to get the new channel - NDR Mecklenburg-Vorpommern HD - please ?
It would be great!
Thank you

**Comment by Free-IPTV** [comment]
Hi @CustomerJFK,

Homepage mit Firefox aufrufen:

https://www.ndr.de/fernsehen/livestream/livestream221.html

Rechte Maustaste - Menü "Untersuchen". Dann Netzwerkanalyse - Medien auswählen, Stream starten.

Immer die .master.m3u oder .index nehmen! Nicht den Chunklist Müll oder etc. Das haben so einige Clowns bei Kodinerds bis heute nicht kapiert. 

https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=652252#post652252

https://www.kodinerds.net/index.php/Thread/56713-Kodinerds-IPTV-Fertige-Liste-mit-freien-IPTV-Kan%C3%A4len/?postID=651948#post651948

Die Master hat quasi eine Ausfallsicherheit, fällt ein Stream mal aus, wird automatisch die nächste niedrigere Auflösung genommen! ;-)

Ich denke, das kannst du nun alleine, findest dann das: 

https://mcdn.ndr.de/ndr/hls/ndr_fs/ndr_mv/master.m3u8

Grüße

Free-IPTV

**Comment by CustomerJFK** [comment]
Hallo
Vielen Dank für die schnelle Info.
Es scheint trotzdem irgentwie nicht zu funktionieren.
Ich komme nur zu dieser Adresse. : https://mcdn.ndr.de/ndr/hls/ndr_fs/ndr_mv/master.m3u8 
Aber der Stream startet im VLC nicht.
Könnte jemnad helfen? Wo liegt der Fehler?
Vielen Dank!

**Comment by Free-IPTV** [comment]
> Es scheint trotzdem irgentwie nicht zu funktionieren.

Seltsam, läuft bei mir problemlos im VLC-Player und in Kodi 18.9 und auch in Matrix.

**Comment by CustomerJFK** [comment]
Hallo 
Auch diese Adresse ging nicht.....
Ich habe dann diese Kombi versucht... (Try and Error ;-))
"https://ndrfs-lh.akamaihd.net/i/ndrfs_mv@430232/master.m3u8"
Jetzt geht es - aber diese Adresse finde ich eigentlich nicht im Firefox... ???? (nach obigen Ablauf)
Wo/Wie findet man diese Adresse eigentlich nun genau?
Beste Grüße und Vielen Dank!

**Comment by CustomerJFK** [comment]
Vielen Dank für die Rückinof - aber der Link: https://mcdn.ndr.de/ndr/hls/ndr_fs/ndr_mv/master.m3u8 fuktioniert bei mir nicht im VLC. - keine Ahnung warum... Aber egal - meine Konstruktion funktioniert ja auch.  (Wobei die Adresse - "https://ndrfs-lh.akamaihd.net/i/ndrfs_mv@430232/master.m3u8"- ja auch anders ist.... ) Aber diese Adresse entspricht auch mehr der unter Germany enthaltenen IP-TV-Adresse von NDR.?! Also muss es doch noch einen anderen Weg geben, um diese Adresse zu finden - Oder....  ???
Aber erstmal fuktioniert es ...  Danke für die Hilfe...
Würde mich trotzdem freuen, zu erfahren wie/wo man diese Adresse findet.: "https://ndrfs-lh.akamaihd.net/i/ndrfs_mv@430232/master.m3u8" .

**Comment by Free-IPTV** [comment]
> Würde mich trotzdem freuen, zu erfahren wie/wo man diese Adresse findet.: "https://ndrfs-lh.akamaihd.net/i/ndrfs_mv@430232/master.m3u8" .

Wahrscheinlich über die App vom ARD ausgelesen, über Heimnetz geht das ja, z.B. mit Wireshark. Smartphone ode TV-Box im Heinmetz und PC/Notebook mit Wireshark im Heimnetz. Damit kann man von jeder App die Streams finden. Issue mach ich nun zu, ist ja erledigt. ;-)
