### ISSUE TITLE
World

### ISSUE THREAD

**Issue by periakatak** [Free-IPTV/Countries#431]

**Comment by periakatak** [comment]
Delete

**Comment by Free-IPTV** [comment]
@Ghost, du Volldiot hast es immer noch nicht kapiert. Du bist wegen deinen illegalen Tätigkeiten hier bei Github bei mir blockert. Dein Issue dit deinem geklauten Kontp Periakata hat zwar funktioniert, als du dann auf den Konto Ghost gewechselt hast, warst du SOFORT blockiert. Deine Vorgehensweise ist nicht nur illegal sondern auch so richtig dumm und amaterurhaft! DU VOLLIDIOT!
