### ISSUE TITLE
Are IPTV lists still being updated?

### ISSUE THREAD

**Issue by fparri** [Free-IPTV/Countries#433]
Hi guys, i read that lists are still being updated, even if not on github. Can I still contribuite to them?

Sorry for the disturb and please let me know :)

**Comment by Free-IPTV** [comment]
> 
> 
> Hi guys, i read that lists are still being updated, even if not on github. Can I still contribuite to them?
> 
> Sorry for the disturb and please let me know :)

Hi Fparri,

sorry, no more updates. M3u's are only left in my region, friends I also know personally. No more public M3U's, sorry....

**Comment by fparri** [comment]
> Hi Fparri,
> 
> sorry, no more updates. M3u's are only left in my region, friends I also know personally. No more public M3U's, sorry....

No problems, sorry for the disturb :)
