### ISSUE TITLE
some channels behind a password lock

### ISSUE THREAD

**Issue by foxy-1423** [Free-IPTV/Countries#434]
The Czech TV channels Nova Action, Prima Cool , and Prima Love are behind a password lock.
![bilde](https://user-images.githubusercontent.com/21003272/140921078-9b98e14d-051f-4cd0-a0c2-1ac033306b16.png)

**Comment by Free-IPTV** [comment]
> 
> 
> The Czech TV channels Nova Action, Prima Cool , and Prima Love are behind a password lock. ![bilde](https://user-images.githubusercontent.com/21003272/140921078-9b98e14d-051f-4cd0-a0c2-1ac033306b16.png)

Das ist mir doch egal! Kannst du nicht lesen??? Es gibt hier keine Updates mehr!

**Comment by foxy-1423** [comment]
oh, my bad, it wasn't in the readme and it looked active.
