### ISSUE TITLE
free chanels of Joyn (Germany) (not Premium)

### ISSUE THREAD

**Issue by CustomerJFK** [Free-IPTV/Countries#53]
Hi
Ist there a way to include the free chanels of Joyn (Germany) as a mu3 list?
best regards
JFK

**Comment by Free-IPTV** [comment]
Hi JFK,

you cannot receive the streams from Joyn via an M3U. Some streams, such as ARD, ZDF and so on, can be received via the original addresses of the transmitters via M3U anyway. The private channels such as Pro7, RTL and so on cannot be freely received via an M3U. For this you need an account with Joyn, Waipu, Zattoo and so on. You have to pay for better quality. I only offer freely available and free streams.

Greetings. :-)

**Comment by CustomerJFK** [comment]
OK - Understood!
Thanks!
