### ISSUE TITLE
Please include the locals

### ISSUE THREAD

**Issue by CHJ85** [Free-IPTV/Countries#54]
Hi there. Do you think you could please add the STiRR City channels please?
Thanks in advance.
And also, please update Pluto TV. There are some new ones there such as Comedy Central Animation.

**Comment by Free-IPTV** [comment]
Hi CHJ85,

I added Stirr City and Comedy Central Animation. The best thing to do is to give me the names of the new channels, especially for Pluto. Then I don't have to look so long. ;-)

Greetings

**Comment by GrouikGrouik** [comment]
Firstly, thanks for your work.

Could you please add MDR THÜRINGEN? 
Thanks in advance

**Comment by Free-IPTV** [comment]
Hi GrouikGrouik,

Added MDR THÜRINGEN. :-)

**Comment by CHJ85** [comment]
Thanks for your work!
Much appreciated.

**Comment by CHJ85** [comment]
I looked through your Pluto TV list, and there are some channels missing here and there and some channels are no longer working.
So to save you work, you might wanna pull your updates from this: https://techzyon.com/epg/plutotv.m3u
This m3u is updated using Pluto TV's API, so it's always up to date.
As for STiRR, same thing: https://techzyon.com/epg/stirr.m3u.
These two m3us also include the EPG.
Also, this does not include the Stirr City channels. Stirr has different Stirr City channels depending on what city you're in.
Not sure which one you added. You see. Stirr have partnered up with CBS and FOX to bring local news to their City channels.
Going through all of them will take forever, so I doubt you'll be willing to do that.
So if I get some free time I can do probably that and get back to you. Then perhaps you could create a separate m3u for Stirr City channels. Just an idea.

**Comment by Free-IPTV** [comment]
Hi CHJ85,

is much to do in Pluto TV USA. If you want, you can help in this part. Make a Fork of my Repo. In your Fork you can change, add and remove streams and then you make a pull-request.

If you add streams to in your current fork and make a pull request, please note the following:

    1. Pay attention to the alphabetical order (0-9. A-Z).
    2. Add the same Group-Name, it is the Country
    3. Do not add any GEO-Blocked streams, the streams in my M3U's can be seen by anyone, anywhere.
    4. Don't add illegal streams. But there are idiots who already do it and then give the name Kodi a bad reputation with the ignorant.

I'm always grateful for any help, it's a lot of work. If everything fits, your pull request will also be accepted. :-)

**Comment by CHJ85** [comment]
@Free-IPTV Right. Yea, I'll go ahead and do that for you.
