### ISSUE TITLE
Wrong group name for "Tele Quebec" in Canada playlist

### ISSUE THREAD

**Issue by greenmr** [Free-IPTV/Countries#55]
As described in title. All other streams in CA01_CANADA.m3u are grouped under "Canada", but the one for "Tele Quebec" is "Kanada". Obviously this also affects ZZ_PLAYLIST_ALL_TV.m3u.

Thanks for this great resource.

**Comment by Free-IPTV** [comment]
Hi greenmr,

i has change the group-name an added some channels. :-)
