### ISSUE TITLE
Taiwan M3u not working. Needs to be overhauled as no channels active

### ISSUE THREAD

**Issue by YesTrustMe** [Free-IPTV/Countries#65]
See above (post title)

**Comment by Free-IPTV** [comment]
Hi YesTrustMe,

okay, thanks for your Info. Ich gehe die Streams durch und mache ein Update.

Greetings

**Comment by Free-IPTV** [comment]
Update is done. They keep changing their YouTube ID. Channels that do that too often will be out of here soon anyway.
