### ISSUE TITLE
Please add  the following countries...

### ISSUE THREAD

**Issue by YesTrustMe** [Free-IPTV/Countries#66]
Kodi has IPTV for Croatia eg. Kodi Balkan Add-On has them. Most of the channels are working, no VPN needed.

**Comment by Free-IPTV** [comment]
Hi YesTrustMe,

with all M3U's there are now about 2900 streams in my repo. They all have to be looked after. So I unfortunately don't have time to create more M3Us. You are welcome to participate here. Create a fork of my repo, upload your file, make a pull request and take care of the file. But first read the text (readme) in my repo. 

Greetings from Germany
