### ISSUE TITLE
What about the walking deas esp channel?

### ISSUE THREAD

**Issue by Mario156090** [Free-IPTV/Countries#68]
Today I try watch this channel bit always me different content instead TWD espisodies.

**Comment by Free-IPTV** [comment]
This is premium content, broadcast by Foxchannels, for example. There is no such thing as free TV. I only have serious streams, you're on the wrong side!

You are also apparently one of those who think premium content is free to watch, something like that is illegal and punishable!

**Comment by Free-IPTV** [comment]
I just looked again. Pluto is currently offering Walking Dead ESP only in Latino!
