### ISSUE TITLE
NEW ITALIAN STREAMS

### ISSUE THREAD

**Issue by robgarib** [Free-IPTV/Countries#71]
I send you some new Italian working streams:
RTTR TRENTO 
https://5f204aff97bee.streamlock.net/RTTRlive/livestream/playlist.m3u8
TRENTINO TV
https://5e73cf528f404.streamlock.net/TrentinoTV/livestream/chunklist_w26373810.m3u8
BERGAMO TV
http://api.new.livestream.com/accounts/245066/events/3063596/live.m3u8
ESPANSIONE TV COMO
https://srvx1.selftv.video/espansione/live/chunklist_w946499575.m3u8

**Comment by Free-IPTV** [comment]
Hi robgarib,

thanks for the new streams. I changed the address of some of them. If possible, always use the chunklist. *. It is always better to have a master, index or playlist.m3u8 address. I'll upload IT01_ITALY right away.

Greeting from German

#EXTINF:-1 tvg-id="" tvg-name="Bergamo TV" tvg-logo="https://i.imgur.com/6jNbS4e.png" group-title="ITALY",Bergamo TV
http://api.new.livestream.com/accounts/245066/events/3063596/live.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Espansione TV Como" tvg-logo="https://i.imgur.com/G3TdZAi.jpg" group-title="ITALY",Espansione TV Como
https://srvx1.selftv.video/espansione/live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="RTTR Trento" tvg-logo="https://i.imgur.com/9houwTS.png" group-title="ITALY",RTTR Trento
https://5f204aff97bee.streamlock.net/RTTRlive/livestream/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Trentino TV" tvg-logo="https://i.imgur.com/2paGMKT.jpg" group-title="ITALY",Trentino TV
https://5e73cf528f404.streamlock.net/TrentinoTV/livestream/playlist.m3u8
