### ISSUE TITLE
EPG Data for Plex?

### ISSUE THREAD

**Issue by eqpaisley** [Free-IPTV/Countries#87]
Curious if there's a way to get guide data for the plex streams in XML format?

**Comment by Free-IPTV** [comment]
Hi  eqpaisley,

here you find EPG for some Streams/Provider:

https://techzyon.com/epg/

https://i.mjh.nz/

I haven't found anything else at the moment.

Greetings from Germany

**Comment by CHJ85** [comment]
@eqpaisley A Plex EPG would be excellent. In the meantime though, the STIRR EPG should cover most of the channels. https://i.mjh.nz/Stirr/epg.xml
