### ISSUE TITLE
Research

### ISSUE THREAD

**Issue by aldo7410** [Free-IPTV/Countries#95]
Hello and thank you for this list of wonderful channels ....
I'm looking for these channels if you can help me, I can't find the urls ..... motorvision, motorsport, motorracing tv, Ric and Boat show .... thank you and good luck to you .. ..

**Comment by Free-IPTV** [comment]
Hi Aldo,

some of the channels in my m3u´s. Italian or so... Motorvision. These channels also in the Samsung TV Plus. Some of these files you you find there.

https://forums.whirlpool.net.au/thread/9nk6qzy3

The channels motorvision, motorsport, motorracing tv, Ric and Boat show for the Streams for germany i dont have at this time but they are comming soon in my DE05_SG_TV_PLUS.

Greetings from Germany.

**Comment by aldo7410** [comment]
Thank you very much dear friend for your help, I seek by logical deduction the streams by testing with VLC, I happen to find things .... In the meantime, thank you for the link which is very good and good job to all .. ...

**Comment by Free-IPTV** [comment]
Okay, thank you also. :-)
