### ISSUE TITLE
French channels

### ISSUE THREAD

**Issue by aldo7410** [Free-IPTV/Countries#96]
Hello and thank you for your great work ....
I'm still looking for the French Samsung tv list, the following channels, Motorvision, Motorracing, Motorsport, HorizoSports, Rictv and Monarda arts .... thank you if you can help me ....

**Comment by Free-IPTV** [comment]
Hi Aldo,

i don´t habe these streams for france in the moment. About Motovision i has olny 1 stream, it´s in the m3u for canada;

https://dai2-xumo.fubo.tv/amagi_hls_data_xumo1212A-motorvisiontv/CDN/master.m3u8

Greetings from Germany

**Comment by aldo7410** [comment]
Thank you friend from Germany, a neighboring country, I am on the border of Switzerland near Mont-Blanc ....
I saw the url of canada for motorvision, I'm looking for how to adapt the sound in French, because I saw with VLC several language levels ..... greetings from France .....

**Comment by Free-IPTV** [comment]
Okay. :-)

**Comment by Free-IPTV** [comment]
Hi Aldo,

i has seen, in the Forum in NZ, you has the streams where you missed. Can you give me this streams. I put it in the FR01-France for all. :-)

Thank you

**Comment by aldo7410** [comment]
Hello, sorry, I do not understand what you are asking me, probably a translation problem ....

**Comment by Free-IPTV** [comment]
Hi Aldo,

you has wrote on the top... **the following channels, Motorvision, Motorracing, Motorsport, HorizoSports, Rictv and Monarda arts ....**

Did you found this streams? I has in the moment no equipment, no Samsung TV, to find this streams. When you has found this streams, can you post it here for me? Then i can add this streams to the M3U for France.

Greetings from Germany.

**Comment by aldo7410** [comment]
Yes, okay, but for the moment it's complicated, I don't have a Smart TV and I have to go through intermediaries and a little complicated at home with COVID ..... have a nice day .....

**Comment by CHJ85** [comment]
@aldo7410 PlutoTV just launched in France.
Maybe you'll be able to find something there.

**Comment by Free-IPTV** [comment]
Hi CHJ85,

we already have so many streams from Pluto TV, USA, Brazil and Germany. The quality of Pluto is abysmal, the streams often break off during advertising. As long as Pluto does not improve its quality and stability, I will not record further streams for other countries from Pluto. We now have over 3000 streams here and I need time to check them, update them and find new streams for the existing M3Us. No new Pluto-M3U at the moment, please. Thank you

**Comment by CHJ85** [comment]
@Free-IPTV Right. I'm just pointing out for @aldo7410 that he can probably find some of his favorite shows there.
But I do tend to agree with you. The thing about Pluto is they broadcast the same channels with different audio track and commercial break depending on which country you live in. So if the tags deviceLat and deviceLon (altitude and latitude) are not included in the URL, you're gonna see ads that are best fit according to your IP address.
